if not exists(select * from [City])
BEGIN
INSERT INTO [City](Name,State,Population) VALUES ('New York','New York',8405837);
INSERT INTO [City](Name,State,Population) VALUES ('Los Angeles','California',3884307);
INSERT INTO [City](Name,State,Population) VALUES ('Chicago','Illinois',2718782);
INSERT INTO [City](Name,State,Population) VALUES ('Houston','Texas',2195914);
INSERT INTO [City](Name,State,Population) VALUES ('Philadelphia','Pennsylvania',1553165);
INSERT INTO [City](Name,State,Population) VALUES ('Phoenix','Arizona',1513367);
INSERT INTO [City](Name,State,Population) VALUES ('San Antonio','Texas',1409019);
INSERT INTO [City](Name,State,Population) VALUES ('San Diego','California',1355896);
INSERT INTO [City](Name,State,Population) VALUES ('Dallas','Texas',1257676);
INSERT INTO [City](Name,State,Population) VALUES ('San Jose','California',998537);
INSERT INTO [City](Name,State,Population) VALUES ('Austin','Texas',885400);
INSERT INTO [City](Name,State,Population) VALUES ('Indianapolis','Indiana',843393);
INSERT INTO [City](Name,State,Population) VALUES ('Jacksonville','Florida',842583);
INSERT INTO [City](Name,State,Population) VALUES ('San Francisco','California',837442);
INSERT INTO [City](Name,State,Population) VALUES ('Columbus','Ohio',822553);
INSERT INTO [City](Name,State,Population) VALUES ('Charlotte','North Carolina',792862);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Worth','Texas',792727);
INSERT INTO [City](Name,State,Population) VALUES ('Detroit','Michigan',688701);
INSERT INTO [City](Name,State,Population) VALUES ('El Paso','Texas',674433);
INSERT INTO [City](Name,State,Population) VALUES ('Memphis','Tennessee',653450);
INSERT INTO [City](Name,State,Population) VALUES ('Seattle','Washington',652405);
INSERT INTO [City](Name,State,Population) VALUES ('Denver','Colorado',649495);
INSERT INTO [City](Name,State,Population) VALUES ('Washington','District of Columbia',646449);
INSERT INTO [City](Name,State,Population) VALUES ('Boston','Massachusetts',645966);
INSERT INTO [City](Name,State,Population) VALUES ('Nashville-Davidson','Tennessee',634464);
INSERT INTO [City](Name,State,Population) VALUES ('Baltimore','Maryland',622104);
INSERT INTO [City](Name,State,Population) VALUES ('Oklahoma City','Oklahoma',610613);
INSERT INTO [City](Name,State,Population) VALUES ('Louisville/Jefferson County','Kentucky',609893);
INSERT INTO [City](Name,State,Population) VALUES ('Portland','Oregon',609456);
INSERT INTO [City](Name,State,Population) VALUES ('Las Vegas','Nevada',603488);
INSERT INTO [City](Name,State,Population) VALUES ('Milwaukee','Wisconsin',599164);
INSERT INTO [City](Name,State,Population) VALUES ('Albuquerque','New Mexico',556495);
INSERT INTO [City](Name,State,Population) VALUES ('Tucson','Arizona',526116);
INSERT INTO [City](Name,State,Population) VALUES ('Fresno','California',509924);
INSERT INTO [City](Name,State,Population) VALUES ('Sacramento','California',479686);
INSERT INTO [City](Name,State,Population) VALUES ('Long Beach','California',469428);
INSERT INTO [City](Name,State,Population) VALUES ('Kansas City','Missouri',467007);
INSERT INTO [City](Name,State,Population) VALUES ('Mesa','Arizona',457587);
INSERT INTO [City](Name,State,Population) VALUES ('Virginia Beach','Virginia',448479);
INSERT INTO [City](Name,State,Population) VALUES ('Atlanta','Georgia',447841);
INSERT INTO [City](Name,State,Population) VALUES ('Colorado Springs','Colorado',439886);
INSERT INTO [City](Name,State,Population) VALUES ('Omaha','Nebraska',434353);
INSERT INTO [City](Name,State,Population) VALUES ('Raleigh','North Carolina',431746);
INSERT INTO [City](Name,State,Population) VALUES ('Miami','Florida',417650);
INSERT INTO [City](Name,State,Population) VALUES ('Oakland','California',406253);
INSERT INTO [City](Name,State,Population) VALUES ('Minneapolis','Minnesota',400070);
INSERT INTO [City](Name,State,Population) VALUES ('Tulsa','Oklahoma',398121);
INSERT INTO [City](Name,State,Population) VALUES ('Cleveland','Ohio',390113);
INSERT INTO [City](Name,State,Population) VALUES ('Wichita','Kansas',386552);
INSERT INTO [City](Name,State,Population) VALUES ('Arlington','Texas',379577);
INSERT INTO [City](Name,State,Population) VALUES ('New Orleans','Louisiana',378715);
INSERT INTO [City](Name,State,Population) VALUES ('Bakersfield','California',363630);
INSERT INTO [City](Name,State,Population) VALUES ('Tampa','Florida',352957);
INSERT INTO [City](Name,State,Population) VALUES ('Honolulu','Hawaii',347884);
INSERT INTO [City](Name,State,Population) VALUES ('Aurora','Colorado',345803);
INSERT INTO [City](Name,State,Population) VALUES ('Anaheim','California',345012);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Ana','California',334227);
INSERT INTO [City](Name,State,Population) VALUES ('St. Louis','Missouri',318416);
INSERT INTO [City](Name,State,Population) VALUES ('Riverside','California',316619);
INSERT INTO [City](Name,State,Population) VALUES ('Corpus Christi','Texas',316381);
INSERT INTO [City](Name,State,Population) VALUES ('Lexington-Fayette','Kentucky',308428);
INSERT INTO [City](Name,State,Population) VALUES ('Pittsburgh','Pennsylvania',305841);
INSERT INTO [City](Name,State,Population) VALUES ('Anchorage','Alaska',300950);
INSERT INTO [City](Name,State,Population) VALUES ('Stockton','California',298118);
INSERT INTO [City](Name,State,Population) VALUES ('Cincinnati','Ohio',297517);
INSERT INTO [City](Name,State,Population) VALUES ('St. Paul','Minnesota',294873);
INSERT INTO [City](Name,State,Population) VALUES ('Toledo','Ohio',282313);
INSERT INTO [City](Name,State,Population) VALUES ('Greensboro','North Carolina',279639);
INSERT INTO [City](Name,State,Population) VALUES ('Newark','New Jersey',278427);
INSERT INTO [City](Name,State,Population) VALUES ('Plano','Texas',274409);
INSERT INTO [City](Name,State,Population) VALUES ('Henderson','Nevada',270811);
INSERT INTO [City](Name,State,Population) VALUES ('Lincoln','Nebraska',268738);
INSERT INTO [City](Name,State,Population) VALUES ('Buffalo','New York',258959);
INSERT INTO [City](Name,State,Population) VALUES ('Jersey City','New Jersey',257342);
INSERT INTO [City](Name,State,Population) VALUES ('Chula Vista','California',256780);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Wayne','Indiana',256496);
INSERT INTO [City](Name,State,Population) VALUES ('Orlando','Florida',255483);
INSERT INTO [City](Name,State,Population) VALUES ('St. Petersburg','Florida',249688);
INSERT INTO [City](Name,State,Population) VALUES ('Chandler','Arizona',249146);
INSERT INTO [City](Name,State,Population) VALUES ('Laredo','Texas',248142);
INSERT INTO [City](Name,State,Population) VALUES ('Norfolk','Virginia',246139);
INSERT INTO [City](Name,State,Population) VALUES ('Durham','North Carolina',245475);
INSERT INTO [City](Name,State,Population) VALUES ('Madison','Wisconsin',243344);
INSERT INTO [City](Name,State,Population) VALUES ('Lubbock','Texas',239538);
INSERT INTO [City](Name,State,Population) VALUES ('Irvine','California',236716);
INSERT INTO [City](Name,State,Population) VALUES ('Winston-Salem','North Carolina',236441);
INSERT INTO [City](Name,State,Population) VALUES ('Glendale','Arizona',234632);
INSERT INTO [City](Name,State,Population) VALUES ('Garland','Texas',234566);
INSERT INTO [City](Name,State,Population) VALUES ('Hialeah','Florida',233394);
INSERT INTO [City](Name,State,Population) VALUES ('Reno','Nevada',233294);
INSERT INTO [City](Name,State,Population) VALUES ('Chesapeake','Virginia',230571);
INSERT INTO [City](Name,State,Population) VALUES ('Gilbert','Arizona',229972);
INSERT INTO [City](Name,State,Population) VALUES ('Baton Rouge','Louisiana',229426);
INSERT INTO [City](Name,State,Population) VALUES ('Irving','Texas',228653);
INSERT INTO [City](Name,State,Population) VALUES ('Scottsdale','Arizona',226918);
INSERT INTO [City](Name,State,Population) VALUES ('North Las Vegas','Nevada',226877);
INSERT INTO [City](Name,State,Population) VALUES ('Fremont','California',224922);
INSERT INTO [City](Name,State,Population) VALUES ('Boise City','Idaho',214237);
INSERT INTO [City](Name,State,Population) VALUES ('Richmond','Virginia',214114);
INSERT INTO [City](Name,State,Population) VALUES ('San Bernardino','California',213708);
INSERT INTO [City](Name,State,Population) VALUES ('Birmingham','Alabama',212113);
INSERT INTO [City](Name,State,Population) VALUES ('Spokane','Washington',210721);
INSERT INTO [City](Name,State,Population) VALUES ('Rochester','New York',210358);
INSERT INTO [City](Name,State,Population) VALUES ('Des Moines','Iowa',207510);
INSERT INTO [City](Name,State,Population) VALUES ('Modesto','California',204933);
INSERT INTO [City](Name,State,Population) VALUES ('Fayetteville','North Carolina',204408);
INSERT INTO [City](Name,State,Population) VALUES ('Tacoma','Washington',203446);
INSERT INTO [City](Name,State,Population) VALUES ('Oxnard','California',203007);
INSERT INTO [City](Name,State,Population) VALUES ('Fontana','California',203003);
INSERT INTO [City](Name,State,Population) VALUES ('Columbus','Georgia',202824);
INSERT INTO [City](Name,State,Population) VALUES ('Montgomery','Alabama',201332);
INSERT INTO [City](Name,State,Population) VALUES ('Moreno Valley','California',201175);
INSERT INTO [City](Name,State,Population) VALUES ('Shreveport','Louisiana',200327);
INSERT INTO [City](Name,State,Population) VALUES ('Aurora','Illinois',199963);
INSERT INTO [City](Name,State,Population) VALUES ('Yonkers','New York',199766);
INSERT INTO [City](Name,State,Population) VALUES ('Akron','Ohio',198100);
INSERT INTO [City](Name,State,Population) VALUES ('Huntington Beach','California',197575);
INSERT INTO [City](Name,State,Population) VALUES ('Little Rock','Arkansas',197357);
INSERT INTO [City](Name,State,Population) VALUES ('Augusta-Richmond County','Georgia',197350);
INSERT INTO [City](Name,State,Population) VALUES ('Amarillo','Texas',196429);
INSERT INTO [City](Name,State,Population) VALUES ('Glendale','California',196021);
INSERT INTO [City](Name,State,Population) VALUES ('Mobile','Alabama',194899);
INSERT INTO [City](Name,State,Population) VALUES ('Grand Rapids','Michigan',192294);
INSERT INTO [City](Name,State,Population) VALUES ('Salt Lake City','Utah',191180);
INSERT INTO [City](Name,State,Population) VALUES ('Tallahassee','Florida',186411);
INSERT INTO [City](Name,State,Population) VALUES ('Huntsville','Alabama',186254);
INSERT INTO [City](Name,State,Population) VALUES ('Grand Prairie','Texas',183372);
INSERT INTO [City](Name,State,Population) VALUES ('Knoxville','Tennessee',183270);
INSERT INTO [City](Name,State,Population) VALUES ('Worcester','Massachusetts',182544);
INSERT INTO [City](Name,State,Population) VALUES ('Newport News','Virginia',182020);
INSERT INTO [City](Name,State,Population) VALUES ('Brownsville','Texas',181860);
INSERT INTO [City](Name,State,Population) VALUES ('Overland Park','Kansas',181260);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Clarita','California',179590);
INSERT INTO [City](Name,State,Population) VALUES ('Providence','Rhode Island',177994);
INSERT INTO [City](Name,State,Population) VALUES ('Garden Grove','California',175140);
INSERT INTO [City](Name,State,Population) VALUES ('Chattanooga','Tennessee',173366);
INSERT INTO [City](Name,State,Population) VALUES ('Oceanside','California',172794);
INSERT INTO [City](Name,State,Population) VALUES ('Jackson','Mississippi',172638);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Lauderdale','Florida',172389);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Rosa','California',171990);
INSERT INTO [City](Name,State,Population) VALUES ('Rancho Cucamonga','California',171386);
INSERT INTO [City](Name,State,Population) VALUES ('Port St. Lucie','Florida',171016);
INSERT INTO [City](Name,State,Population) VALUES ('Tempe','Arizona',168228);
INSERT INTO [City](Name,State,Population) VALUES ('Ontario','California',167500);
INSERT INTO [City](Name,State,Population) VALUES ('Vancouver','Washington',167405);
INSERT INTO [City](Name,State,Population) VALUES ('Cape Coral','Florida',165831);
INSERT INTO [City](Name,State,Population) VALUES ('Sioux Falls','South Dakota',164676);
INSERT INTO [City](Name,State,Population) VALUES ('Springfield','Missouri',164122);
INSERT INTO [City](Name,State,Population) VALUES ('Peoria','Arizona',162592);
INSERT INTO [City](Name,State,Population) VALUES ('Pembroke Pines','Florida',162329);
INSERT INTO [City](Name,State,Population) VALUES ('Elk Grove','California',161007);
INSERT INTO [City](Name,State,Population) VALUES ('Salem','Oregon',160614);
INSERT INTO [City](Name,State,Population) VALUES ('Lancaster','California',159523);
INSERT INTO [City](Name,State,Population) VALUES ('Corona','California',159503);
INSERT INTO [City](Name,State,Population) VALUES ('Eugene','Oregon',159190);
INSERT INTO [City](Name,State,Population) VALUES ('Palmdale','California',157161);
INSERT INTO [City](Name,State,Population) VALUES ('Salinas','California',155662);
INSERT INTO [City](Name,State,Population) VALUES ('Springfield','Massachusetts',153703);
INSERT INTO [City](Name,State,Population) VALUES ('Pasadena','Texas',152735);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Collins','Colorado',152061);
INSERT INTO [City](Name,State,Population) VALUES ('Hayward','California',151574);
INSERT INTO [City](Name,State,Population) VALUES ('Pomona','California',151348);
INSERT INTO [City](Name,State,Population) VALUES ('Cary','North Carolina',151088);
INSERT INTO [City](Name,State,Population) VALUES ('Rockford','Illinois',150251);
INSERT INTO [City](Name,State,Population) VALUES ('Alexandria','Virginia',148892);
INSERT INTO [City](Name,State,Population) VALUES ('Escondido','California',148738);
INSERT INTO [City](Name,State,Population) VALUES ('McKinney','Texas',148559);
INSERT INTO [City](Name,State,Population) VALUES ('Kansas City','Kansas',148483);
INSERT INTO [City](Name,State,Population) VALUES ('Joliet','Illinois',147806);
INSERT INTO [City](Name,State,Population) VALUES ('Sunnyvale','California',147559);
INSERT INTO [City](Name,State,Population) VALUES ('Torrance','California',147478);
INSERT INTO [City](Name,State,Population) VALUES ('Bridgeport','Connecticut',147216);
INSERT INTO [City](Name,State,Population) VALUES ('Lakewood','Colorado',147214);
INSERT INTO [City](Name,State,Population) VALUES ('Hollywood','Florida',146526);
INSERT INTO [City](Name,State,Population) VALUES ('Paterson','New Jersey',145948);
INSERT INTO [City](Name,State,Population) VALUES ('Naperville','Illinois',144864);
INSERT INTO [City](Name,State,Population) VALUES ('Syracuse','New York',144669);
INSERT INTO [City](Name,State,Population) VALUES ('Mesquite','Texas',143484);
INSERT INTO [City](Name,State,Population) VALUES ('Dayton','Ohio',143355);
INSERT INTO [City](Name,State,Population) VALUES ('Savannah','Georgia',142772);
INSERT INTO [City](Name,State,Population) VALUES ('Clarksville','Tennessee',142357);
INSERT INTO [City](Name,State,Population) VALUES ('Orange','California',139969);
INSERT INTO [City](Name,State,Population) VALUES ('Pasadena','California',139731);
INSERT INTO [City](Name,State,Population) VALUES ('Fullerton','California',138981);
INSERT INTO [City](Name,State,Population) VALUES ('Killeen','Texas',137147);
INSERT INTO [City](Name,State,Population) VALUES ('Frisco','Texas',136791);
INSERT INTO [City](Name,State,Population) VALUES ('Hampton','Virginia',136699);
INSERT INTO [City](Name,State,Population) VALUES ('McAllen','Texas',136639);
INSERT INTO [City](Name,State,Population) VALUES ('Warren','Michigan',134873);
INSERT INTO [City](Name,State,Population) VALUES ('Bellevue','Washington',133992);
INSERT INTO [City](Name,State,Population) VALUES ('West Valley City','Utah',133579);
INSERT INTO [City](Name,State,Population) VALUES ('Columbia','South Carolina',133358);
INSERT INTO [City](Name,State,Population) VALUES ('Olathe','Kansas',131885);
INSERT INTO [City](Name,State,Population) VALUES ('Sterling Heights','Michigan',131224);
INSERT INTO [City](Name,State,Population) VALUES ('New Haven','Connecticut',130660);
INSERT INTO [City](Name,State,Population) VALUES ('Miramar','Florida',130288);
INSERT INTO [City](Name,State,Population) VALUES ('Waco','Texas',129030);
INSERT INTO [City](Name,State,Population) VALUES ('Thousand Oaks','California',128731);
INSERT INTO [City](Name,State,Population) VALUES ('Cedar Rapids','Iowa',128429);
INSERT INTO [City](Name,State,Population) VALUES ('Charleston','South Carolina',127999);
INSERT INTO [City](Name,State,Population) VALUES ('Visalia','California',127763);
INSERT INTO [City](Name,State,Population) VALUES ('Topeka','Kansas',127679);
INSERT INTO [City](Name,State,Population) VALUES ('Elizabeth','New Jersey',127558);
INSERT INTO [City](Name,State,Population) VALUES ('Gainesville','Florida',127488);
INSERT INTO [City](Name,State,Population) VALUES ('Thornton','Colorado',127359);
INSERT INTO [City](Name,State,Population) VALUES ('Roseville','California',127035);
INSERT INTO [City](Name,State,Population) VALUES ('Carrollton','Texas',126700);
INSERT INTO [City](Name,State,Population) VALUES ('Coral Springs','Florida',126604);
INSERT INTO [City](Name,State,Population) VALUES ('Stamford','Connecticut',126456);
INSERT INTO [City](Name,State,Population) VALUES ('Simi Valley','California',126181);
INSERT INTO [City](Name,State,Population) VALUES ('Concord','California',125880);
INSERT INTO [City](Name,State,Population) VALUES ('Hartford','Connecticut',125017);
INSERT INTO [City](Name,State,Population) VALUES ('Kent','Washington',124435);
INSERT INTO [City](Name,State,Population) VALUES ('Lafayette','Louisiana',124276);
INSERT INTO [City](Name,State,Population) VALUES ('Midland','Texas',123933);
INSERT INTO [City](Name,State,Population) VALUES ('Surprise','Arizona',123546);
INSERT INTO [City](Name,State,Population) VALUES ('Denton','Texas',123099);
INSERT INTO [City](Name,State,Population) VALUES ('Victorville','California',121096);
INSERT INTO [City](Name,State,Population) VALUES ('Evansville','Indiana',120310);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Clara','California',120245);
INSERT INTO [City](Name,State,Population) VALUES ('Abilene','Texas',120099);
INSERT INTO [City](Name,State,Population) VALUES ('Athens-Clarke County','Georgia',119980);
INSERT INTO [City](Name,State,Population) VALUES ('Vallejo','California',118837);
INSERT INTO [City](Name,State,Population) VALUES ('Allentown','Pennsylvania',118577);
INSERT INTO [City](Name,State,Population) VALUES ('Norman','Oklahoma',118197);
INSERT INTO [City](Name,State,Population) VALUES ('Beaumont','Texas',117796);
INSERT INTO [City](Name,State,Population) VALUES ('Independence','Missouri',117240);
INSERT INTO [City](Name,State,Population) VALUES ('Murfreesboro','Tennessee',117044);
INSERT INTO [City](Name,State,Population) VALUES ('Ann Arbor','Michigan',117025);
INSERT INTO [City](Name,State,Population) VALUES ('Springfield','Illinois',117006);
INSERT INTO [City](Name,State,Population) VALUES ('Berkeley','California',116768);
INSERT INTO [City](Name,State,Population) VALUES ('Peoria','Illinois',116513);
INSERT INTO [City](Name,State,Population) VALUES ('Provo','Utah',116288);
INSERT INTO [City](Name,State,Population) VALUES ('El Monte','California',115708);
INSERT INTO [City](Name,State,Population) VALUES ('Columbia','Missouri',115276);
INSERT INTO [City](Name,State,Population) VALUES ('Lansing','Michigan',113972);
INSERT INTO [City](Name,State,Population) VALUES ('Fargo','North Dakota',113658);
INSERT INTO [City](Name,State,Population) VALUES ('Downey','California',113242);
INSERT INTO [City](Name,State,Population) VALUES ('Costa Mesa','California',112174);
INSERT INTO [City](Name,State,Population) VALUES ('Wilmington','North Carolina',112067);
INSERT INTO [City](Name,State,Population) VALUES ('Arvada','Colorado',111707);
INSERT INTO [City](Name,State,Population) VALUES ('Inglewood','California',111542);
INSERT INTO [City](Name,State,Population) VALUES ('Miami Gardens','Florida',111378);
INSERT INTO [City](Name,State,Population) VALUES ('Carlsbad','California',110972);
INSERT INTO [City](Name,State,Population) VALUES ('Westminster','Colorado',110945);
INSERT INTO [City](Name,State,Population) VALUES ('Rochester','Minnesota',110742);
INSERT INTO [City](Name,State,Population) VALUES ('Odessa','Texas',110720);
INSERT INTO [City](Name,State,Population) VALUES ('Manchester','New Hampshire',110378);
INSERT INTO [City](Name,State,Population) VALUES ('Elgin','Illinois',110145);
INSERT INTO [City](Name,State,Population) VALUES ('West Jordan','Utah',110077);
INSERT INTO [City](Name,State,Population) VALUES ('Round Rock','Texas',109821);
INSERT INTO [City](Name,State,Population) VALUES ('Clearwater','Florida',109703);
INSERT INTO [City](Name,State,Population) VALUES ('Waterbury','Connecticut',109676);
INSERT INTO [City](Name,State,Population) VALUES ('Gresham','Oregon',109397);
INSERT INTO [City](Name,State,Population) VALUES ('Fairfield','California',109320);
INSERT INTO [City](Name,State,Population) VALUES ('Billings','Montana',109059);
INSERT INTO [City](Name,State,Population) VALUES ('Lowell','Massachusetts',108861);
INSERT INTO [City](Name,State,Population) VALUES ('San Buenaventura (Ventura)','California',108817);
INSERT INTO [City](Name,State,Population) VALUES ('Pueblo','Colorado',108249);
INSERT INTO [City](Name,State,Population) VALUES ('High Point','North Carolina',107741);
INSERT INTO [City](Name,State,Population) VALUES ('West Covina','California',107740);
INSERT INTO [City](Name,State,Population) VALUES ('Richmond','California',107571);
INSERT INTO [City](Name,State,Population) VALUES ('Murrieta','California',107479);
INSERT INTO [City](Name,State,Population) VALUES ('Cambridge','Massachusetts',107289);
INSERT INTO [City](Name,State,Population) VALUES ('Antioch','California',107100);
INSERT INTO [City](Name,State,Population) VALUES ('Temecula','California',106780);
INSERT INTO [City](Name,State,Population) VALUES ('Norwalk','California',106589);
INSERT INTO [City](Name,State,Population) VALUES ('Centennial','Colorado',106114);
INSERT INTO [City](Name,State,Population) VALUES ('Everett','Washington',105370);
INSERT INTO [City](Name,State,Population) VALUES ('Palm Bay','Florida',104898);
INSERT INTO [City](Name,State,Population) VALUES ('Wichita Falls','Texas',104898);
INSERT INTO [City](Name,State,Population) VALUES ('Green Bay','Wisconsin',104779);
INSERT INTO [City](Name,State,Population) VALUES ('Daly City','California',104739);
INSERT INTO [City](Name,State,Population) VALUES ('Burbank','California',104709);
INSERT INTO [City](Name,State,Population) VALUES ('Richardson','Texas',104475);
INSERT INTO [City](Name,State,Population) VALUES ('Pompano Beach','Florida',104410);
INSERT INTO [City](Name,State,Population) VALUES ('North Charleston','South Carolina',104054);
INSERT INTO [City](Name,State,Population) VALUES ('Broken Arrow','Oklahoma',103500);
INSERT INTO [City](Name,State,Population) VALUES ('Boulder','Colorado',103166);
INSERT INTO [City](Name,State,Population) VALUES ('West Palm Beach','Florida',102436);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Maria','California',102216);
INSERT INTO [City](Name,State,Population) VALUES ('El Cajon','California',102211);
INSERT INTO [City](Name,State,Population) VALUES ('Davenport','Iowa',102157);
INSERT INTO [City](Name,State,Population) VALUES ('Rialto','California',101910);
INSERT INTO [City](Name,State,Population) VALUES ('Las Cruces','New Mexico',101324);
INSERT INTO [City](Name,State,Population) VALUES ('San Mateo','California',101128);
INSERT INTO [City](Name,State,Population) VALUES ('Lewisville','Texas',101074);
INSERT INTO [City](Name,State,Population) VALUES ('South Bend','Indiana',100886);
INSERT INTO [City](Name,State,Population) VALUES ('Lakeland','Florida',100710);
INSERT INTO [City](Name,State,Population) VALUES ('Erie','Pennsylvania',100671);
INSERT INTO [City](Name,State,Population) VALUES ('Tyler','Texas',100223);
INSERT INTO [City](Name,State,Population) VALUES ('Pearland','Texas',100065);
INSERT INTO [City](Name,State,Population) VALUES ('College Station','Texas',100050);
INSERT INTO [City](Name,State,Population) VALUES ('Kenosha','Wisconsin',99889);
INSERT INTO [City](Name,State,Population) VALUES ('Sandy Springs','Georgia',99770);
INSERT INTO [City](Name,State,Population) VALUES ('Clovis','California',99769);
INSERT INTO [City](Name,State,Population) VALUES ('Flint','Michigan',99763);
INSERT INTO [City](Name,State,Population) VALUES ('Roanoke','Virginia',98465);
INSERT INTO [City](Name,State,Population) VALUES ('Albany','New York',98424);
INSERT INTO [City](Name,State,Population) VALUES ('Jurupa Valley','California',98030);
INSERT INTO [City](Name,State,Population) VALUES ('Compton','California',97877);
INSERT INTO [City](Name,State,Population) VALUES ('San Angelo','Texas',97492);
INSERT INTO [City](Name,State,Population) VALUES ('Hillsboro','Oregon',97368);
INSERT INTO [City](Name,State,Population) VALUES ('Lawton','Oklahoma',97151);
INSERT INTO [City](Name,State,Population) VALUES ('Renton','Washington',97003);
INSERT INTO [City](Name,State,Population) VALUES ('Vista','California',96929);
INSERT INTO [City](Name,State,Population) VALUES ('Davie','Florida',96830);
INSERT INTO [City](Name,State,Population) VALUES ('Greeley','Colorado',96539);
INSERT INTO [City](Name,State,Population) VALUES ('Mission Viejo','California',96346);
INSERT INTO [City](Name,State,Population) VALUES ('Portsmouth','Virginia',96205);
INSERT INTO [City](Name,State,Population) VALUES ('Dearborn','Michigan',95884);
INSERT INTO [City](Name,State,Population) VALUES ('South Gate','California',95677);
INSERT INTO [City](Name,State,Population) VALUES ('Tuscaloosa','Alabama',95334);
INSERT INTO [City](Name,State,Population) VALUES ('Livonia','Michigan',95208);
INSERT INTO [City](Name,State,Population) VALUES ('New Bedford','Massachusetts',95078);
INSERT INTO [City](Name,State,Population) VALUES ('Vacaville','California',94275);
INSERT INTO [City](Name,State,Population) VALUES ('Brockton','Massachusetts',94089);
INSERT INTO [City](Name,State,Population) VALUES ('Roswell','Georgia',94034);
INSERT INTO [City](Name,State,Population) VALUES ('Beaverton','Oregon',93542);
INSERT INTO [City](Name,State,Population) VALUES ('Quincy','Massachusetts',93494);
INSERT INTO [City](Name,State,Population) VALUES ('Sparks','Nevada',93282);
INSERT INTO [City](Name,State,Population) VALUES ('Yakima','Washington',93257);
INSERT INTO [City](Name,State,Population) VALUES ('Lee''s Summit','Missouri',93184);
INSERT INTO [City](Name,State,Population) VALUES ('Federal Way','Washington',92734);
INSERT INTO [City](Name,State,Population) VALUES ('Carson','California',92599);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Monica','California',92472);
INSERT INTO [City](Name,State,Population) VALUES ('Hesperia','California',92147);
INSERT INTO [City](Name,State,Population) VALUES ('Allen','Texas',92020);
INSERT INTO [City](Name,State,Population) VALUES ('Rio Rancho','New Mexico',91956);
INSERT INTO [City](Name,State,Population) VALUES ('Yuma','Arizona',91923);
INSERT INTO [City](Name,State,Population) VALUES ('Westminster','California',91739);
INSERT INTO [City](Name,State,Population) VALUES ('Orem','Utah',91648);
INSERT INTO [City](Name,State,Population) VALUES ('Lynn','Massachusetts',91589);
INSERT INTO [City](Name,State,Population) VALUES ('Redding','California',91119);
INSERT INTO [City](Name,State,Population) VALUES ('Spokane Valley','Washington',91113);
INSERT INTO [City](Name,State,Population) VALUES ('Miami Beach','Florida',91026);
INSERT INTO [City](Name,State,Population) VALUES ('League City','Texas',90983);
INSERT INTO [City](Name,State,Population) VALUES ('Lawrence','Kansas',90811);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Barbara','California',90412);
INSERT INTO [City](Name,State,Population) VALUES ('Plantation','Florida',90268);
INSERT INTO [City](Name,State,Population) VALUES ('Sandy','Utah',90231);
INSERT INTO [City](Name,State,Population) VALUES ('Sunrise','Florida',90116);
INSERT INTO [City](Name,State,Population) VALUES ('Macon','Georgia',89981);
INSERT INTO [City](Name,State,Population) VALUES ('Longmont','Colorado',89919);
INSERT INTO [City](Name,State,Population) VALUES ('Boca Raton','Florida',89407);
INSERT INTO [City](Name,State,Population) VALUES ('San Marcos','California',89387);
INSERT INTO [City](Name,State,Population) VALUES ('Greenville','North Carolina',89130);
INSERT INTO [City](Name,State,Population) VALUES ('Waukegan','Illinois',88826);
INSERT INTO [City](Name,State,Population) VALUES ('Fall River','Massachusetts',88697);
INSERT INTO [City](Name,State,Population) VALUES ('Chico','California',88077);
INSERT INTO [City](Name,State,Population) VALUES ('Newton','Massachusetts',87971);
INSERT INTO [City](Name,State,Population) VALUES ('San Leandro','California',87965);
INSERT INTO [City](Name,State,Population) VALUES ('Reading','Pennsylvania',87893);
INSERT INTO [City](Name,State,Population) VALUES ('Norwalk','Connecticut',87776);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Smith','Arkansas',87650);
INSERT INTO [City](Name,State,Population) VALUES ('Newport Beach','California',87273);
INSERT INTO [City](Name,State,Population) VALUES ('Asheville','North Carolina',87236);
INSERT INTO [City](Name,State,Population) VALUES ('Nashua','New Hampshire',87137);
INSERT INTO [City](Name,State,Population) VALUES ('Edmond','Oklahoma',87004);
INSERT INTO [City](Name,State,Population) VALUES ('Whittier','California',86635);
INSERT INTO [City](Name,State,Population) VALUES ('Nampa','Idaho',86518);
INSERT INTO [City](Name,State,Population) VALUES ('Bloomington','Minnesota',86319);
INSERT INTO [City](Name,State,Population) VALUES ('Deltona','Florida',86290);
INSERT INTO [City](Name,State,Population) VALUES ('Hawthorne','California',86199);
INSERT INTO [City](Name,State,Population) VALUES ('Duluth','Minnesota',86128);
INSERT INTO [City](Name,State,Population) VALUES ('Carmel','Indiana',85927);
INSERT INTO [City](Name,State,Population) VALUES ('Suffolk','Virginia',85728);
INSERT INTO [City](Name,State,Population) VALUES ('Clifton','New Jersey',85390);
INSERT INTO [City](Name,State,Population) VALUES ('Citrus Heights','California',85285);
INSERT INTO [City](Name,State,Population) VALUES ('Livermore','California',85156);
INSERT INTO [City](Name,State,Population) VALUES ('Tracy','California',84691);
INSERT INTO [City](Name,State,Population) VALUES ('Alhambra','California',84577);
INSERT INTO [City](Name,State,Population) VALUES ('Kirkland','Washington',84430);
INSERT INTO [City](Name,State,Population) VALUES ('Trenton','New Jersey',84349);
INSERT INTO [City](Name,State,Population) VALUES ('Ogden','Utah',84249);
INSERT INTO [City](Name,State,Population) VALUES ('Hoover','Alabama',84126);
INSERT INTO [City](Name,State,Population) VALUES ('Cicero','Illinois',84103);
INSERT INTO [City](Name,State,Population) VALUES ('Fishers','Indiana',83891);
INSERT INTO [City](Name,State,Population) VALUES ('Sugar Land','Texas',83860);
INSERT INTO [City](Name,State,Population) VALUES ('Danbury','Connecticut',83684);
INSERT INTO [City](Name,State,Population) VALUES ('Meridian','Idaho',83596);
INSERT INTO [City](Name,State,Population) VALUES ('Indio','California',83539);
INSERT INTO [City](Name,State,Population) VALUES ('Concord','North Carolina',83506);
INSERT INTO [City](Name,State,Population) VALUES ('Menifee','California',83447);
INSERT INTO [City](Name,State,Population) VALUES ('Champaign','Illinois',83424);
INSERT INTO [City](Name,State,Population) VALUES ('Buena Park','California',82882);
INSERT INTO [City](Name,State,Population) VALUES ('Troy','Michigan',82821);
INSERT INTO [City](Name,State,Population) VALUES ('O''Fallon','Missouri',82809);
INSERT INTO [City](Name,State,Population) VALUES ('Johns Creek','Georgia',82788);
INSERT INTO [City](Name,State,Population) VALUES ('Bellingham','Washington',82631);
INSERT INTO [City](Name,State,Population) VALUES ('Westland','Michigan',82578);
INSERT INTO [City](Name,State,Population) VALUES ('Bloomington','Indiana',82575);
INSERT INTO [City](Name,State,Population) VALUES ('Sioux City','Iowa',82459);
INSERT INTO [City](Name,State,Population) VALUES ('Warwick','Rhode Island',81971);
INSERT INTO [City](Name,State,Population) VALUES ('Hemet','California',81750);
INSERT INTO [City](Name,State,Population) VALUES ('Longview','Texas',81443);
INSERT INTO [City](Name,State,Population) VALUES ('Farmington Hills','Michigan',81295);
INSERT INTO [City](Name,State,Population) VALUES ('Bend','Oregon',81236);
INSERT INTO [City](Name,State,Population) VALUES ('Lakewood','California',81121);
INSERT INTO [City](Name,State,Population) VALUES ('Merced','California',81102);
INSERT INTO [City](Name,State,Population) VALUES ('Mission','Texas',81050);
INSERT INTO [City](Name,State,Population) VALUES ('Chino','California',80988);
INSERT INTO [City](Name,State,Population) VALUES ('Redwood City','California',80872);
INSERT INTO [City](Name,State,Population) VALUES ('Edinburg','Texas',80836);
INSERT INTO [City](Name,State,Population) VALUES ('Cranston','Rhode Island',80566);
INSERT INTO [City](Name,State,Population) VALUES ('Parma','Ohio',80429);
INSERT INTO [City](Name,State,Population) VALUES ('New Rochelle','New York',79446);
INSERT INTO [City](Name,State,Population) VALUES ('Lake Forest','California',79312);
INSERT INTO [City](Name,State,Population) VALUES ('Napa','California',79068);
INSERT INTO [City](Name,State,Population) VALUES ('Hammond','Indiana',78967);
INSERT INTO [City](Name,State,Population) VALUES ('Fayetteville','Arkansas',78960);
INSERT INTO [City](Name,State,Population) VALUES ('Bloomington','Illinois',78902);
INSERT INTO [City](Name,State,Population) VALUES ('Avondale','Arizona',78822);
INSERT INTO [City](Name,State,Population) VALUES ('Somerville','Massachusetts',78804);
INSERT INTO [City](Name,State,Population) VALUES ('Palm Coast','Florida',78740);
INSERT INTO [City](Name,State,Population) VALUES ('Bryan','Texas',78709);
INSERT INTO [City](Name,State,Population) VALUES ('Gary','Indiana',78450);
INSERT INTO [City](Name,State,Population) VALUES ('Largo','Florida',78409);
INSERT INTO [City](Name,State,Population) VALUES ('Brooklyn Park','Minnesota',78373);
INSERT INTO [City](Name,State,Population) VALUES ('Tustin','California',78327);
INSERT INTO [City](Name,State,Population) VALUES ('Racine','Wisconsin',78199);
INSERT INTO [City](Name,State,Population) VALUES ('Deerfield Beach','Florida',78041);
INSERT INTO [City](Name,State,Population) VALUES ('Lynchburg','Virginia',78014);
INSERT INTO [City](Name,State,Population) VALUES ('Mountain View','California',77846);
INSERT INTO [City](Name,State,Population) VALUES ('Medford','Oregon',77677);
INSERT INTO [City](Name,State,Population) VALUES ('Lawrence','Massachusetts',77657);
INSERT INTO [City](Name,State,Population) VALUES ('Bellflower','California',77593);
INSERT INTO [City](Name,State,Population) VALUES ('Melbourne','Florida',77508);
INSERT INTO [City](Name,State,Population) VALUES ('St. Joseph','Missouri',77147);
INSERT INTO [City](Name,State,Population) VALUES ('Camden','New Jersey',76903);
INSERT INTO [City](Name,State,Population) VALUES ('St. George','Utah',76817);
INSERT INTO [City](Name,State,Population) VALUES ('Kennewick','Washington',76762);
INSERT INTO [City](Name,State,Population) VALUES ('Baldwin Park','California',76635);
INSERT INTO [City](Name,State,Population) VALUES ('Chino Hills','California',76572);
INSERT INTO [City](Name,State,Population) VALUES ('Alameda','California',76419);
INSERT INTO [City](Name,State,Population) VALUES ('Albany','Georgia',76185);
INSERT INTO [City](Name,State,Population) VALUES ('Arlington Heights','Illinois',75994);
INSERT INTO [City](Name,State,Population) VALUES ('Scranton','Pennsylvania',75806);
INSERT INTO [City](Name,State,Population) VALUES ('Evanston','Illinois',75570);
INSERT INTO [City](Name,State,Population) VALUES ('Kalamazoo','Michigan',75548);
INSERT INTO [City](Name,State,Population) VALUES ('Baytown','Texas',75418);
INSERT INTO [City](Name,State,Population) VALUES ('Upland','California',75413);
INSERT INTO [City](Name,State,Population) VALUES ('Springdale','Arkansas',75229);
INSERT INTO [City](Name,State,Population) VALUES ('Bethlehem','Pennsylvania',75018);
INSERT INTO [City](Name,State,Population) VALUES ('Schaumburg','Illinois',74907);
INSERT INTO [City](Name,State,Population) VALUES ('Mount Pleasant','South Carolina',74885);
INSERT INTO [City](Name,State,Population) VALUES ('Auburn','Washington',74860);
INSERT INTO [City](Name,State,Population) VALUES ('Decatur','Illinois',74710);
INSERT INTO [City](Name,State,Population) VALUES ('San Ramon','California',74513);
INSERT INTO [City](Name,State,Population) VALUES ('Pleasanton','California',74110);
INSERT INTO [City](Name,State,Population) VALUES ('Wyoming','Michigan',74100);
INSERT INTO [City](Name,State,Population) VALUES ('Lake Charles','Louisiana',74024);
INSERT INTO [City](Name,State,Population) VALUES ('Plymouth','Minnesota',73987);
INSERT INTO [City](Name,State,Population) VALUES ('Bolingbrook','Illinois',73936);
INSERT INTO [City](Name,State,Population) VALUES ('Pharr','Texas',73790);
INSERT INTO [City](Name,State,Population) VALUES ('Appleton','Wisconsin',73596);
INSERT INTO [City](Name,State,Population) VALUES ('Gastonia','North Carolina',73209);
INSERT INTO [City](Name,State,Population) VALUES ('Folsom','California',73098);
INSERT INTO [City](Name,State,Population) VALUES ('Southfield','Michigan',73006);
INSERT INTO [City](Name,State,Population) VALUES ('Rochester Hills','Michigan',72952);
INSERT INTO [City](Name,State,Population) VALUES ('New Britain','Connecticut',72939);
INSERT INTO [City](Name,State,Population) VALUES ('Goodyear','Arizona',72864);
INSERT INTO [City](Name,State,Population) VALUES ('Canton','Ohio',72535);
INSERT INTO [City](Name,State,Population) VALUES ('Warner Robins','Georgia',72531);
INSERT INTO [City](Name,State,Population) VALUES ('Union City','California',72528);
INSERT INTO [City](Name,State,Population) VALUES ('Perris','California',72326);
INSERT INTO [City](Name,State,Population) VALUES ('Manteca','California',71948);
INSERT INTO [City](Name,State,Population) VALUES ('Iowa City','Iowa',71591);
INSERT INTO [City](Name,State,Population) VALUES ('Jonesboro','Arkansas',71551);
INSERT INTO [City](Name,State,Population) VALUES ('Wilmington','Delaware',71525);
INSERT INTO [City](Name,State,Population) VALUES ('Lynwood','California',71371);
INSERT INTO [City](Name,State,Population) VALUES ('Loveland','Colorado',71334);
INSERT INTO [City](Name,State,Population) VALUES ('Pawtucket','Rhode Island',71172);
INSERT INTO [City](Name,State,Population) VALUES ('Boynton Beach','Florida',71097);
INSERT INTO [City](Name,State,Population) VALUES ('Waukesha','Wisconsin',71016);
INSERT INTO [City](Name,State,Population) VALUES ('Gulfport','Mississippi',71012);
INSERT INTO [City](Name,State,Population) VALUES ('Apple Valley','California',70924);
INSERT INTO [City](Name,State,Population) VALUES ('Passaic','New Jersey',70868);
INSERT INTO [City](Name,State,Population) VALUES ('Rapid City','South Dakota',70812);
INSERT INTO [City](Name,State,Population) VALUES ('Layton','Utah',70790);
INSERT INTO [City](Name,State,Population) VALUES ('Lafayette','Indiana',70373);
INSERT INTO [City](Name,State,Population) VALUES ('Turlock','California',70365);
INSERT INTO [City](Name,State,Population) VALUES ('Muncie','Indiana',70316);
INSERT INTO [City](Name,State,Population) VALUES ('Temple','Texas',70190);
INSERT INTO [City](Name,State,Population) VALUES ('Missouri City','Texas',70185);
INSERT INTO [City](Name,State,Population) VALUES ('Redlands','California',69999);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Fe','New Mexico',69976);
INSERT INTO [City](Name,State,Population) VALUES ('Lauderhill','Florida',69813);
INSERT INTO [City](Name,State,Population) VALUES ('Milpitas','California',69783);
INSERT INTO [City](Name,State,Population) VALUES ('Palatine','Illinois',69350);
INSERT INTO [City](Name,State,Population) VALUES ('Missoula','Montana',69122);
INSERT INTO [City](Name,State,Population) VALUES ('Rock Hill','South Carolina',69103);
INSERT INTO [City](Name,State,Population) VALUES ('Jacksonville','North Carolina',69079);
INSERT INTO [City](Name,State,Population) VALUES ('Franklin','Tennessee',68886);
INSERT INTO [City](Name,State,Population) VALUES ('Flagstaff','Arizona',68667);
INSERT INTO [City](Name,State,Population) VALUES ('Flower Mound','Texas',68609);
INSERT INTO [City](Name,State,Population) VALUES ('Weston','Florida',68388);
INSERT INTO [City](Name,State,Population) VALUES ('Waterloo','Iowa',68366);
INSERT INTO [City](Name,State,Population) VALUES ('Union City','New Jersey',68247);
INSERT INTO [City](Name,State,Population) VALUES ('Mount Vernon','New York',68224);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Myers','Florida',68190);
INSERT INTO [City](Name,State,Population) VALUES ('Dothan','Alabama',68001);
INSERT INTO [City](Name,State,Population) VALUES ('Rancho Cordova','California',67911);
INSERT INTO [City](Name,State,Population) VALUES ('Redondo Beach','California',67815);
INSERT INTO [City](Name,State,Population) VALUES ('Jackson','Tennessee',67685);
INSERT INTO [City](Name,State,Population) VALUES ('Pasco','Washington',67599);
INSERT INTO [City](Name,State,Population) VALUES ('St. Charles','Missouri',67569);
INSERT INTO [City](Name,State,Population) VALUES ('Eau Claire','Wisconsin',67545);
INSERT INTO [City](Name,State,Population) VALUES ('North Richland Hills','Texas',67317);
INSERT INTO [City](Name,State,Population) VALUES ('Bismarck','North Dakota',67034);
INSERT INTO [City](Name,State,Population) VALUES ('Yorba Linda','California',67032);
INSERT INTO [City](Name,State,Population) VALUES ('Kenner','Louisiana',66975);
INSERT INTO [City](Name,State,Population) VALUES ('Walnut Creek','California',66900);
INSERT INTO [City](Name,State,Population) VALUES ('Frederick','Maryland',66893);
INSERT INTO [City](Name,State,Population) VALUES ('Oshkosh','Wisconsin',66778);
INSERT INTO [City](Name,State,Population) VALUES ('Pittsburg','California',66695);
INSERT INTO [City](Name,State,Population) VALUES ('Palo Alto','California',66642);
INSERT INTO [City](Name,State,Population) VALUES ('Bossier City','Louisiana',66333);
INSERT INTO [City](Name,State,Population) VALUES ('Portland','Maine',66318);
INSERT INTO [City](Name,State,Population) VALUES ('St. Cloud','Minnesota',66297);
INSERT INTO [City](Name,State,Population) VALUES ('Davis','California',66205);
INSERT INTO [City](Name,State,Population) VALUES ('South San Francisco','California',66174);
INSERT INTO [City](Name,State,Population) VALUES ('Camarillo','California',66086);
INSERT INTO [City](Name,State,Population) VALUES ('North Little Rock','Arkansas',66075);
INSERT INTO [City](Name,State,Population) VALUES ('Schenectady','New York',65902);
INSERT INTO [City](Name,State,Population) VALUES ('Gaithersburg','Maryland',65690);
INSERT INTO [City](Name,State,Population) VALUES ('Harlingen','Texas',65665);
INSERT INTO [City](Name,State,Population) VALUES ('Woodbury','Minnesota',65656);
INSERT INTO [City](Name,State,Population) VALUES ('Eagan','Minnesota',65453);
INSERT INTO [City](Name,State,Population) VALUES ('Yuba City','California',65416);
INSERT INTO [City](Name,State,Population) VALUES ('Maple Grove','Minnesota',65415);
INSERT INTO [City](Name,State,Population) VALUES ('Youngstown','Ohio',65184);
INSERT INTO [City](Name,State,Population) VALUES ('Skokie','Illinois',65176);
INSERT INTO [City](Name,State,Population) VALUES ('Kissimmee','Florida',65173);
INSERT INTO [City](Name,State,Population) VALUES ('Johnson City','Tennessee',65123);
INSERT INTO [City](Name,State,Population) VALUES ('Victoria','Texas',65098);
INSERT INTO [City](Name,State,Population) VALUES ('San Clemente','California',65040);
INSERT INTO [City](Name,State,Population) VALUES ('Bayonne','New Jersey',65028);
INSERT INTO [City](Name,State,Population) VALUES ('Laguna Niguel','California',64652);
INSERT INTO [City](Name,State,Population) VALUES ('East Orange','New Jersey',64544);
INSERT INTO [City](Name,State,Population) VALUES ('Shawnee','Kansas',64323);
INSERT INTO [City](Name,State,Population) VALUES ('Homestead','Florida',64079);
INSERT INTO [City](Name,State,Population) VALUES ('Rockville','Maryland',64072);
INSERT INTO [City](Name,State,Population) VALUES ('Delray Beach','Florida',64072);
INSERT INTO [City](Name,State,Population) VALUES ('Janesville','Wisconsin',63820);
INSERT INTO [City](Name,State,Population) VALUES ('Conway','Arkansas',63816);
INSERT INTO [City](Name,State,Population) VALUES ('Pico Rivera','California',63771);
INSERT INTO [City](Name,State,Population) VALUES ('Lorain','Ohio',63710);
INSERT INTO [City](Name,State,Population) VALUES ('Montebello','California',63495);
INSERT INTO [City](Name,State,Population) VALUES ('Lodi','California',63338);
INSERT INTO [City](Name,State,Population) VALUES ('New Braunfels','Texas',63279);
INSERT INTO [City](Name,State,Population) VALUES ('Marysville','Washington',63269);
INSERT INTO [City](Name,State,Population) VALUES ('Tamarac','Florida',63155);
INSERT INTO [City](Name,State,Population) VALUES ('Madera','California',63105);
INSERT INTO [City](Name,State,Population) VALUES ('Conroe','Texas',63032);
INSERT INTO [City](Name,State,Population) VALUES ('Santa Cruz','California',62864);
INSERT INTO [City](Name,State,Population) VALUES ('Eden Prairie','Minnesota',62603);
INSERT INTO [City](Name,State,Population) VALUES ('Cheyenne','Wyoming',62448);
INSERT INTO [City](Name,State,Population) VALUES ('Daytona Beach','Florida',62316);
INSERT INTO [City](Name,State,Population) VALUES ('Alpharetta','Georgia',62298);
INSERT INTO [City](Name,State,Population) VALUES ('Hamilton','Ohio',62258);
INSERT INTO [City](Name,State,Population) VALUES ('Waltham','Massachusetts',62227);
INSERT INTO [City](Name,State,Population) VALUES ('Coon Rapids','Minnesota',62103);
INSERT INTO [City](Name,State,Population) VALUES ('Haverhill','Massachusetts',62088);
INSERT INTO [City](Name,State,Population) VALUES ('Council Bluffs','Iowa',61969);
INSERT INTO [City](Name,State,Population) VALUES ('Taylor','Michigan',61817);
INSERT INTO [City](Name,State,Population) VALUES ('Utica','New York',61808);
INSERT INTO [City](Name,State,Population) VALUES ('Ames','Iowa',61792);
INSERT INTO [City](Name,State,Population) VALUES ('La Habra','California',61653);
INSERT INTO [City](Name,State,Population) VALUES ('Encinitas','California',61588);
INSERT INTO [City](Name,State,Population) VALUES ('Bowling Green','Kentucky',61488);
INSERT INTO [City](Name,State,Population) VALUES ('Burnsville','Minnesota',61434);
INSERT INTO [City](Name,State,Population) VALUES ('Greenville','South Carolina',61397);
INSERT INTO [City](Name,State,Population) VALUES ('West Des Moines','Iowa',61255);
INSERT INTO [City](Name,State,Population) VALUES ('Cedar Park','Texas',61238);
INSERT INTO [City](Name,State,Population) VALUES ('Tulare','California',61170);
INSERT INTO [City](Name,State,Population) VALUES ('Monterey Park','California',61085);
INSERT INTO [City](Name,State,Population) VALUES ('Vineland','New Jersey',61050);
INSERT INTO [City](Name,State,Population) VALUES ('Terre Haute','Indiana',61025);
INSERT INTO [City](Name,State,Population) VALUES ('North Miami','Florida',61007);
INSERT INTO [City](Name,State,Population) VALUES ('Mansfield','Texas',60872);
INSERT INTO [City](Name,State,Population) VALUES ('West Allis','Wisconsin',60697);
INSERT INTO [City](Name,State,Population) VALUES ('Bristol','Connecticut',60568);
INSERT INTO [City](Name,State,Population) VALUES ('Taylorsville','Utah',60519);
INSERT INTO [City](Name,State,Population) VALUES ('Malden','Massachusetts',60509);
INSERT INTO [City](Name,State,Population) VALUES ('Meriden','Connecticut',60456);
INSERT INTO [City](Name,State,Population) VALUES ('Blaine','Minnesota',60407);
INSERT INTO [City](Name,State,Population) VALUES ('Wellington','Florida',60202);
INSERT INTO [City](Name,State,Population) VALUES ('Cupertino','California',60189);
INSERT INTO [City](Name,State,Population) VALUES ('Springfield','Oregon',60177);
INSERT INTO [City](Name,State,Population) VALUES ('Rogers','Arkansas',60112);
INSERT INTO [City](Name,State,Population) VALUES ('St. Clair Shores','Michigan',60070);
INSERT INTO [City](Name,State,Population) VALUES ('Gardena','California',59957);
INSERT INTO [City](Name,State,Population) VALUES ('Pontiac','Michigan',59887);
INSERT INTO [City](Name,State,Population) VALUES ('National City','California',59834);
INSERT INTO [City](Name,State,Population) VALUES ('Grand Junction','Colorado',59778);
INSERT INTO [City](Name,State,Population) VALUES ('Rocklin','California',59738);
INSERT INTO [City](Name,State,Population) VALUES ('Chapel Hill','North Carolina',59635);
INSERT INTO [City](Name,State,Population) VALUES ('Casper','Wyoming',59628);
INSERT INTO [City](Name,State,Population) VALUES ('Broomfield','Colorado',59471);
INSERT INTO [City](Name,State,Population) VALUES ('Petaluma','California',59440);
INSERT INTO [City](Name,State,Population) VALUES ('South Jordan','Utah',59366);
INSERT INTO [City](Name,State,Population) VALUES ('Springfield','Ohio',59357);
INSERT INTO [City](Name,State,Population) VALUES ('Great Falls','Montana',59351);
INSERT INTO [City](Name,State,Population) VALUES ('Lancaster','Pennsylvania',59325);
INSERT INTO [City](Name,State,Population) VALUES ('North Port','Florida',59212);
INSERT INTO [City](Name,State,Population) VALUES ('Lakewood','Washington',59097);
INSERT INTO [City](Name,State,Population) VALUES ('Marietta','Georgia',59089);
INSERT INTO [City](Name,State,Population) VALUES ('San Rafael','California',58994);
INSERT INTO [City](Name,State,Population) VALUES ('Royal Oak','Michigan',58946);
INSERT INTO [City](Name,State,Population) VALUES ('Des Plaines','Illinois',58918);
INSERT INTO [City](Name,State,Population) VALUES ('Huntington Park','California',58879);
INSERT INTO [City](Name,State,Population) VALUES ('La Mesa','California',58642);
INSERT INTO [City](Name,State,Population) VALUES ('Orland Park','Illinois',58590);
INSERT INTO [City](Name,State,Population) VALUES ('Auburn','Alabama',58582);
INSERT INTO [City](Name,State,Population) VALUES ('Lakeville','Minnesota',58562);
INSERT INTO [City](Name,State,Population) VALUES ('Owensboro','Kentucky',58416);
INSERT INTO [City](Name,State,Population) VALUES ('Moore','Oklahoma',58414);
INSERT INTO [City](Name,State,Population) VALUES ('Jupiter','Florida',58298);
INSERT INTO [City](Name,State,Population) VALUES ('Idaho Falls','Idaho',58292);
INSERT INTO [City](Name,State,Population) VALUES ('Dubuque','Iowa',58253);
INSERT INTO [City](Name,State,Population) VALUES ('Bartlett','Tennessee',58226);
INSERT INTO [City](Name,State,Population) VALUES ('Rowlett','Texas',58043);
INSERT INTO [City](Name,State,Population) VALUES ('Novi','Michigan',57960);
INSERT INTO [City](Name,State,Population) VALUES ('White Plains','New York',57866);
INSERT INTO [City](Name,State,Population) VALUES ('Arcadia','California',57639);
INSERT INTO [City](Name,State,Population) VALUES ('Redmond','Washington',57530);
INSERT INTO [City](Name,State,Population) VALUES ('Lake Elsinore','California',57525);
INSERT INTO [City](Name,State,Population) VALUES ('Ocala','Florida',57468);
INSERT INTO [City](Name,State,Population) VALUES ('Tinley Park','Illinois',57282);
INSERT INTO [City](Name,State,Population) VALUES ('Port Orange','Florida',57203);
INSERT INTO [City](Name,State,Population) VALUES ('Medford','Massachusetts',57170);
INSERT INTO [City](Name,State,Population) VALUES ('Oak Lawn','Illinois',57073);
INSERT INTO [City](Name,State,Population) VALUES ('Rocky Mount','North Carolina',56954);
INSERT INTO [City](Name,State,Population) VALUES ('Kokomo','Indiana',56895);
INSERT INTO [City](Name,State,Population) VALUES ('Coconut Creek','Florida',56792);
INSERT INTO [City](Name,State,Population) VALUES ('Bowie','Maryland',56759);
INSERT INTO [City](Name,State,Population) VALUES ('Berwyn','Illinois',56758);
INSERT INTO [City](Name,State,Population) VALUES ('Midwest City','Oklahoma',56756);
INSERT INTO [City](Name,State,Population) VALUES ('Fountain Valley','California',56707);
INSERT INTO [City](Name,State,Population) VALUES ('Buckeye','Arizona',56683);
INSERT INTO [City](Name,State,Population) VALUES ('Dearborn Heights','Michigan',56620);
INSERT INTO [City](Name,State,Population) VALUES ('Woodland','California',56590);
INSERT INTO [City](Name,State,Population) VALUES ('Noblesville','Indiana',56540);
INSERT INTO [City](Name,State,Population) VALUES ('Valdosta','Georgia',56481);
INSERT INTO [City](Name,State,Population) VALUES ('Diamond Bar','California',56449);
INSERT INTO [City](Name,State,Population) VALUES ('Manhattan','Kansas',56143);
INSERT INTO [City](Name,State,Population) VALUES ('Santee','California',56105);
INSERT INTO [City](Name,State,Population) VALUES ('Taunton','Massachusetts',56069);
INSERT INTO [City](Name,State,Population) VALUES ('Sanford','Florida',56002);
INSERT INTO [City](Name,State,Population) VALUES ('Kettering','Ohio',55870);
INSERT INTO [City](Name,State,Population) VALUES ('New Brunswick','New Jersey',55831);
INSERT INTO [City](Name,State,Population) VALUES ('Decatur','Alabama',55816);
INSERT INTO [City](Name,State,Population) VALUES ('Chicopee','Massachusetts',55717);
INSERT INTO [City](Name,State,Population) VALUES ('Anderson','Indiana',55670);
INSERT INTO [City](Name,State,Population) VALUES ('Margate','Florida',55456);
INSERT INTO [City](Name,State,Population) VALUES ('Weymouth Town','Massachusetts',55419);
INSERT INTO [City](Name,State,Population) VALUES ('Hempstead','New York',55361);
INSERT INTO [City](Name,State,Population) VALUES ('Corvallis','Oregon',55298);
INSERT INTO [City](Name,State,Population) VALUES ('Eastvale','California',55191);
INSERT INTO [City](Name,State,Population) VALUES ('Porterville','California',55174);
INSERT INTO [City](Name,State,Population) VALUES ('West Haven','Connecticut',55046);
INSERT INTO [City](Name,State,Population) VALUES ('Brentwood','California',55000);
INSERT INTO [City](Name,State,Population) VALUES ('Paramount','California',54980);
INSERT INTO [City](Name,State,Population) VALUES ('Grand Forks','North Dakota',54932);
INSERT INTO [City](Name,State,Population) VALUES ('Georgetown','Texas',54898);
INSERT INTO [City](Name,State,Population) VALUES ('St. Peters','Missouri',54842);
INSERT INTO [City](Name,State,Population) VALUES ('Shoreline','Washington',54790);
INSERT INTO [City](Name,State,Population) VALUES ('Mount Prospect','Illinois',54771);
INSERT INTO [City](Name,State,Population) VALUES ('Hanford','California',54686);
INSERT INTO [City](Name,State,Population) VALUES ('Normal','Illinois',54664);
INSERT INTO [City](Name,State,Population) VALUES ('Rosemead','California',54561);
INSERT INTO [City](Name,State,Population) VALUES ('Lehi','Utah',54382);
INSERT INTO [City](Name,State,Population) VALUES ('Pocatello','Idaho',54350);
INSERT INTO [City](Name,State,Population) VALUES ('Highland','California',54291);
INSERT INTO [City](Name,State,Population) VALUES ('Novato','California',54194);
INSERT INTO [City](Name,State,Population) VALUES ('Port Arthur','Texas',54135);
INSERT INTO [City](Name,State,Population) VALUES ('Carson City','Nevada',54080);
INSERT INTO [City](Name,State,Population) VALUES ('San Marcos','Texas',54076);
INSERT INTO [City](Name,State,Population) VALUES ('Hendersonville','Tennessee',54068);
INSERT INTO [City](Name,State,Population) VALUES ('Elyria','Ohio',53956);
INSERT INTO [City](Name,State,Population) VALUES ('Revere','Massachusetts',53756);
INSERT INTO [City](Name,State,Population) VALUES ('Pflugerville','Texas',53752);
INSERT INTO [City](Name,State,Population) VALUES ('Greenwood','Indiana',53665);
INSERT INTO [City](Name,State,Population) VALUES ('Bellevue','Nebraska',53663);
INSERT INTO [City](Name,State,Population) VALUES ('Wheaton','Illinois',53648);
INSERT INTO [City](Name,State,Population) VALUES ('Smyrna','Georgia',53438);
INSERT INTO [City](Name,State,Population) VALUES ('Sarasota','Florida',53326);
INSERT INTO [City](Name,State,Population) VALUES ('Blue Springs','Missouri',53294);
INSERT INTO [City](Name,State,Population) VALUES ('Colton','California',53243);
INSERT INTO [City](Name,State,Population) VALUES ('Euless','Texas',53224);
INSERT INTO [City](Name,State,Population) VALUES ('Castle Rock','Colorado',53063);
INSERT INTO [City](Name,State,Population) VALUES ('Cathedral City','California',52977);
INSERT INTO [City](Name,State,Population) VALUES ('Kingsport','Tennessee',52962);
INSERT INTO [City](Name,State,Population) VALUES ('Lake Havasu City','Arizona',52844);
INSERT INTO [City](Name,State,Population) VALUES ('Pensacola','Florida',52703);
INSERT INTO [City](Name,State,Population) VALUES ('Hoboken','New Jersey',52575);
INSERT INTO [City](Name,State,Population) VALUES ('Yucaipa','California',52536);
INSERT INTO [City](Name,State,Population) VALUES ('Watsonville','California',52477);
INSERT INTO [City](Name,State,Population) VALUES ('Richland','Washington',52413);
INSERT INTO [City](Name,State,Population) VALUES ('Delano','California',52403);
INSERT INTO [City](Name,State,Population) VALUES ('Hoffman Estates','Illinois',52398);
INSERT INTO [City](Name,State,Population) VALUES ('Florissant','Missouri',52363);
INSERT INTO [City](Name,State,Population) VALUES ('Placentia','California',52206);
INSERT INTO [City](Name,State,Population) VALUES ('West New York','New Jersey',52122);
INSERT INTO [City](Name,State,Population) VALUES ('Dublin','California',52105);
INSERT INTO [City](Name,State,Population) VALUES ('Oak Park','Illinois',52066);
INSERT INTO [City](Name,State,Population) VALUES ('Peabody','Massachusetts',52044);
INSERT INTO [City](Name,State,Population) VALUES ('Perth Amboy','New Jersey',51982);
INSERT INTO [City](Name,State,Population) VALUES ('Battle Creek','Michigan',51848);
INSERT INTO [City](Name,State,Population) VALUES ('Bradenton','Florida',51763);
INSERT INTO [City](Name,State,Population) VALUES ('Gilroy','California',51701);
INSERT INTO [City](Name,State,Population) VALUES ('Milford','Connecticut',51644);
INSERT INTO [City](Name,State,Population) VALUES ('Albany','Oregon',51583);
INSERT INTO [City](Name,State,Population) VALUES ('Ankeny','Iowa',51567);
INSERT INTO [City](Name,State,Population) VALUES ('La Crosse','Wisconsin',51522);
INSERT INTO [City](Name,State,Population) VALUES ('Burlington','North Carolina',51510);
INSERT INTO [City](Name,State,Population) VALUES ('DeSoto','Texas',51483);
INSERT INTO [City](Name,State,Population) VALUES ('Harrisonburg','Virginia',51395);
INSERT INTO [City](Name,State,Population) VALUES ('Minnetonka','Minnesota',51368);
INSERT INTO [City](Name,State,Population) VALUES ('Elkhart','Indiana',51265);
INSERT INTO [City](Name,State,Population) VALUES ('Lakewood','Ohio',51143);
INSERT INTO [City](Name,State,Population) VALUES ('Glendora','California',51074);
INSERT INTO [City](Name,State,Population) VALUES ('Southaven','Mississippi',50997);
INSERT INTO [City](Name,State,Population) VALUES ('Charleston','West Virginia',50821);
INSERT INTO [City](Name,State,Population) VALUES ('Joplin','Missouri',50789);
INSERT INTO [City](Name,State,Population) VALUES ('Enid','Oklahoma',50725);
INSERT INTO [City](Name,State,Population) VALUES ('Palm Beach Gardens','Florida',50699);
INSERT INTO [City](Name,State,Population) VALUES ('Brookhaven','Georgia',50603);
INSERT INTO [City](Name,State,Population) VALUES ('Plainfield','New Jersey',50588);
INSERT INTO [City](Name,State,Population) VALUES ('Grand Island','Nebraska',50550);
INSERT INTO [City](Name,State,Population) VALUES ('Palm Desert','California',50508);
INSERT INTO [City](Name,State,Population) VALUES ('Huntersville','North Carolina',50458);
INSERT INTO [City](Name,State,Population) VALUES ('Tigard','Oregon',50444);
INSERT INTO [City](Name,State,Population) VALUES ('Lenexa','Kansas',50344);
INSERT INTO [City](Name,State,Population) VALUES ('Saginaw','Michigan',50303);
INSERT INTO [City](Name,State,Population) VALUES ('Kentwood','Michigan',50233);
INSERT INTO [City](Name,State,Population) VALUES ('Doral','Florida',50213);
INSERT INTO [City](Name,State,Population) VALUES ('Apple Valley','Minnesota',50201);
INSERT INTO [City](Name,State,Population) VALUES ('Grapevine','Texas',50195);
INSERT INTO [City](Name,State,Population) VALUES ('Aliso Viejo','California',50175);
INSERT INTO [City](Name,State,Population) VALUES ('Sammamish','Washington',50169);
INSERT INTO [City](Name,State,Population) VALUES ('Casa Grande','Arizona',50111);
INSERT INTO [City](Name,State,Population) VALUES ('Pinellas Park','Florida',49998);
INSERT INTO [City](Name,State,Population) VALUES ('Troy','New York',49974);
INSERT INTO [City](Name,State,Population) VALUES ('West Sacramento','California',49891);
INSERT INTO [City](Name,State,Population) VALUES ('Burien','Washington',49858);
INSERT INTO [City](Name,State,Population) VALUES ('Commerce City','Colorado',49799);
INSERT INTO [City](Name,State,Population) VALUES ('Monroe','Louisiana',49761);
INSERT INTO [City](Name,State,Population) VALUES ('Cerritos','California',49707);
INSERT INTO [City](Name,State,Population) VALUES ('Downers Grove','Illinois',49670);
INSERT INTO [City](Name,State,Population) VALUES ('Coral Gables','Florida',49631);
INSERT INTO [City](Name,State,Population) VALUES ('Wilson','North Carolina',49628);
INSERT INTO [City](Name,State,Population) VALUES ('Niagara Falls','New York',49468);
INSERT INTO [City](Name,State,Population) VALUES ('Poway','California',49417);
INSERT INTO [City](Name,State,Population) VALUES ('Edina','Minnesota',49376);
INSERT INTO [City](Name,State,Population) VALUES ('Cuyahoga Falls','Ohio',49267);
INSERT INTO [City](Name,State,Population) VALUES ('Rancho Santa Margarita','California',49228);
INSERT INTO [City](Name,State,Population) VALUES ('Harrisburg','Pennsylvania',49188);
INSERT INTO [City](Name,State,Population) VALUES ('Huntington','West Virginia',49177);
INSERT INTO [City](Name,State,Population) VALUES ('La Mirada','California',49133);
INSERT INTO [City](Name,State,Population) VALUES ('Cypress','California',49087);
INSERT INTO [City](Name,State,Population) VALUES ('Caldwell','Idaho',48957);
INSERT INTO [City](Name,State,Population) VALUES ('Logan','Utah',48913);
INSERT INTO [City](Name,State,Population) VALUES ('Galveston','Texas',48733);
INSERT INTO [City](Name,State,Population) VALUES ('Sheboygan','Wisconsin',48725);
INSERT INTO [City](Name,State,Population) VALUES ('Middletown','Ohio',48630);
INSERT INTO [City](Name,State,Population) VALUES ('Murray','Utah',48612);
INSERT INTO [City](Name,State,Population) VALUES ('Roswell','New Mexico',48611);
INSERT INTO [City](Name,State,Population) VALUES ('Parker','Colorado',48608);
INSERT INTO [City](Name,State,Population) VALUES ('Bedford','Texas',48592);
INSERT INTO [City](Name,State,Population) VALUES ('East Lansing','Michigan',48554);
INSERT INTO [City](Name,State,Population) VALUES ('Methuen','Massachusetts',48514);
INSERT INTO [City](Name,State,Population) VALUES ('Covina','California',48508);
INSERT INTO [City](Name,State,Population) VALUES ('Alexandria','Louisiana',48426);
INSERT INTO [City](Name,State,Population) VALUES ('Olympia','Washington',48338);
INSERT INTO [City](Name,State,Population) VALUES ('Euclid','Ohio',48139);
INSERT INTO [City](Name,State,Population) VALUES ('Mishawaka','Indiana',47989);
INSERT INTO [City](Name,State,Population) VALUES ('Salina','Kansas',47846);
INSERT INTO [City](Name,State,Population) VALUES ('Azusa','California',47842);
INSERT INTO [City](Name,State,Population) VALUES ('Newark','Ohio',47777);
INSERT INTO [City](Name,State,Population) VALUES ('Chesterfield','Missouri',47749);
INSERT INTO [City](Name,State,Population) VALUES ('Leesburg','Virginia',47673);
INSERT INTO [City](Name,State,Population) VALUES ('Dunwoody','Georgia',47591);
INSERT INTO [City](Name,State,Population) VALUES ('Hattiesburg','Mississippi',47556);
INSERT INTO [City](Name,State,Population) VALUES ('Roseville','Michigan',47555);
INSERT INTO [City](Name,State,Population) VALUES ('Bonita Springs','Florida',47547);
INSERT INTO [City](Name,State,Population) VALUES ('Portage','Michigan',47523);
INSERT INTO [City](Name,State,Population) VALUES ('St. Louis Park','Minnesota',47411);
INSERT INTO [City](Name,State,Population) VALUES ('Collierville','Tennessee',47333);
INSERT INTO [City](Name,State,Population) VALUES ('Middletown','Connecticut',47333);
INSERT INTO [City](Name,State,Population) VALUES ('Stillwater','Oklahoma',47186);
INSERT INTO [City](Name,State,Population) VALUES ('East Providence','Rhode Island',47149);
INSERT INTO [City](Name,State,Population) VALUES ('Lawrence','Indiana',47135);
INSERT INTO [City](Name,State,Population) VALUES ('Wauwatosa','Wisconsin',47134);
INSERT INTO [City](Name,State,Population) VALUES ('Mentor','Ohio',46979);
INSERT INTO [City](Name,State,Population) VALUES ('Ceres','California',46714);
INSERT INTO [City](Name,State,Population) VALUES ('Cedar Hill','Texas',46663);
INSERT INTO [City](Name,State,Population) VALUES ('Mansfield','Ohio',46454);
INSERT INTO [City](Name,State,Population) VALUES ('Binghamton','New York',46444);
INSERT INTO [City](Name,State,Population) VALUES ('Coeur d''Alene','Idaho',46402);
INSERT INTO [City](Name,State,Population) VALUES ('San Luis Obispo','California',46377);
INSERT INTO [City](Name,State,Population) VALUES ('Minot','North Dakota',46321);
INSERT INTO [City](Name,State,Population) VALUES ('Palm Springs','California',46281);
INSERT INTO [City](Name,State,Population) VALUES ('Pine Bluff','Arkansas',46094);
INSERT INTO [City](Name,State,Population) VALUES ('Texas City','Texas',46081);
INSERT INTO [City](Name,State,Population) VALUES ('Summerville','South Carolina',46074);
INSERT INTO [City](Name,State,Population) VALUES ('Twin Falls','Idaho',45981);
INSERT INTO [City](Name,State,Population) VALUES ('Jeffersonville','Indiana',45929);
INSERT INTO [City](Name,State,Population) VALUES ('San Jacinto','California',45851);
INSERT INTO [City](Name,State,Population) VALUES ('Madison','Alabama',45799);
INSERT INTO [City](Name,State,Population) VALUES ('Altoona','Pennsylvania',45796);
INSERT INTO [City](Name,State,Population) VALUES ('Columbus','Indiana',45775);
INSERT INTO [City](Name,State,Population) VALUES ('Beavercreek','Ohio',45712);
INSERT INTO [City](Name,State,Population) VALUES ('Apopka','Florida',45587);
INSERT INTO [City](Name,State,Population) VALUES ('Elmhurst','Illinois',45556);
INSERT INTO [City](Name,State,Population) VALUES ('Maricopa','Arizona',45508);
INSERT INTO [City](Name,State,Population) VALUES ('Farmington','New Mexico',45426);
INSERT INTO [City](Name,State,Population) VALUES ('Glenview','Illinois',45417);
INSERT INTO [City](Name,State,Population) VALUES ('Cleveland Heights','Ohio',45394);
INSERT INTO [City](Name,State,Population) VALUES ('Draper','Utah',45285);
INSERT INTO [City](Name,State,Population) VALUES ('Lincoln','California',45237);
INSERT INTO [City](Name,State,Population) VALUES ('Sierra Vista','Arizona',45129);
INSERT INTO [City](Name,State,Population) VALUES ('Lacey','Washington',44919);
INSERT INTO [City](Name,State,Population) VALUES ('Biloxi','Mississippi',44820);
INSERT INTO [City](Name,State,Population) VALUES ('Strongsville','Ohio',44730);
INSERT INTO [City](Name,State,Population) VALUES ('Barnstable Town','Massachusetts',44641);
INSERT INTO [City](Name,State,Population) VALUES ('Wylie','Texas',44575);
INSERT INTO [City](Name,State,Population) VALUES ('Sayreville','New Jersey',44412);
INSERT INTO [City](Name,State,Population) VALUES ('Kannapolis','North Carolina',44359);
INSERT INTO [City](Name,State,Population) VALUES ('Charlottesville','Virginia',44349);
INSERT INTO [City](Name,State,Population) VALUES ('Littleton','Colorado',44275);
INSERT INTO [City](Name,State,Population) VALUES ('Titusville','Florida',44206);
INSERT INTO [City](Name,State,Population) VALUES ('Hackensack','New Jersey',44113);
INSERT INTO [City](Name,State,Population) VALUES ('Newark','California',44096);
INSERT INTO [City](Name,State,Population) VALUES ('Pittsfield','Massachusetts',44057);
INSERT INTO [City](Name,State,Population) VALUES ('York','Pennsylvania',43935);
INSERT INTO [City](Name,State,Population) VALUES ('Lombard','Illinois',43907);
INSERT INTO [City](Name,State,Population) VALUES ('Attleboro','Massachusetts',43886);
INSERT INTO [City](Name,State,Population) VALUES ('DeKalb','Illinois',43849);
INSERT INTO [City](Name,State,Population) VALUES ('Blacksburg','Virginia',43609);
INSERT INTO [City](Name,State,Population) VALUES ('Dublin','Ohio',43607);
INSERT INTO [City](Name,State,Population) VALUES ('Haltom City','Texas',43580);
INSERT INTO [City](Name,State,Population) VALUES ('Lompoc','California',43509);
INSERT INTO [City](Name,State,Population) VALUES ('El Centro','California',43363);
INSERT INTO [City](Name,State,Population) VALUES ('Danville','California',43341);
INSERT INTO [City](Name,State,Population) VALUES ('Jefferson City','Missouri',43330);
INSERT INTO [City](Name,State,Population) VALUES ('Cutler Bay','Florida',43328);
INSERT INTO [City](Name,State,Population) VALUES ('Oakland Park','Florida',43286);
INSERT INTO [City](Name,State,Population) VALUES ('North Miami Beach','Florida',43250);
INSERT INTO [City](Name,State,Population) VALUES ('Freeport','New York',43167);
INSERT INTO [City](Name,State,Population) VALUES ('Moline','Illinois',43116);
INSERT INTO [City](Name,State,Population) VALUES ('Coachella','California',43092);
INSERT INTO [City](Name,State,Population) VALUES ('Fort Pierce','Florida',43074);
INSERT INTO [City](Name,State,Population) VALUES ('Smyrna','Tennessee',43060);
INSERT INTO [City](Name,State,Population) VALUES ('Bountiful','Utah',43023);
INSERT INTO [City](Name,State,Population) VALUES ('Fond du Lac','Wisconsin',42970);
INSERT INTO [City](Name,State,Population) VALUES ('Everett','Massachusetts',42935);
INSERT INTO [City](Name,State,Population) VALUES ('Danville','Virginia',42907);
INSERT INTO [City](Name,State,Population) VALUES ('Keller','Texas',42907);
INSERT INTO [City](Name,State,Population) VALUES ('Belleville','Illinois',42895);
INSERT INTO [City](Name,State,Population) VALUES ('Bell Gardens','California',42889);
INSERT INTO [City](Name,State,Population) VALUES ('Cleveland','Tennessee',42774);
INSERT INTO [City](Name,State,Population) VALUES ('North Lauderdale','Florida',42757);
INSERT INTO [City](Name,State,Population) VALUES ('Fairfield','Ohio',42635);
INSERT INTO [City](Name,State,Population) VALUES ('Salem','Massachusetts',42544);
INSERT INTO [City](Name,State,Population) VALUES ('Rancho Palos Verdes','California',42448);
INSERT INTO [City](Name,State,Population) VALUES ('San Bruno','California',42443);
INSERT INTO [City](Name,State,Population) VALUES ('Concord','New Hampshire',42419);
INSERT INTO [City](Name,State,Population) VALUES ('Burlington','Vermont',42284);
INSERT INTO [City](Name,State,Population) VALUES ('Apex','North Carolina',42214);
INSERT INTO [City](Name,State,Population) VALUES ('Midland','Michigan',42181);
INSERT INTO [City](Name,State,Population) VALUES ('Altamonte Springs','Florida',42150);
INSERT INTO [City](Name,State,Population) VALUES ('Hutchinson','Kansas',41889);
INSERT INTO [City](Name,State,Population) VALUES ('Buffalo Grove','Illinois',41778);
INSERT INTO [City](Name,State,Population) VALUES ('Urbandale','Iowa',41776);
INSERT INTO [City](Name,State,Population) VALUES ('State College','Pennsylvania',41757);
INSERT INTO [City](Name,State,Population) VALUES ('Urbana','Illinois',41752);
INSERT INTO [City](Name,State,Population) VALUES ('Plainfield','Illinois',41734);
INSERT INTO [City](Name,State,Population) VALUES ('Manassas','Virginia',41705);
INSERT INTO [City](Name,State,Population) VALUES ('Bartlett','Illinois',41679);
INSERT INTO [City](Name,State,Population) VALUES ('Kearny','New Jersey',41664);
INSERT INTO [City](Name,State,Population) VALUES ('Oro Valley','Arizona',41627);
INSERT INTO [City](Name,State,Population) VALUES ('Findlay','Ohio',41512);
INSERT INTO [City](Name,State,Population) VALUES ('Rohnert Park','California',41398);
INSERT INTO [City](Name,State,Population) VALUES ('Westfield','Massachusetts',41301);
INSERT INTO [City](Name,State,Population) VALUES ('Linden','New Jersey',41301);
INSERT INTO [City](Name,State,Population) VALUES ('Sumter','South Carolina',41190);
INSERT INTO [City](Name,State,Population) VALUES ('Wilkes-Barre','Pennsylvania',41108);
INSERT INTO [City](Name,State,Population) VALUES ('Woonsocket','Rhode Island',41026);
INSERT INTO [City](Name,State,Population) VALUES ('Leominster','Massachusetts',41002);
INSERT INTO [City](Name,State,Population) VALUES ('Shelton','Connecticut',40999);
INSERT INTO [City](Name,State,Population) VALUES ('Brea','California',40963);
INSERT INTO [City](Name,State,Population) VALUES ('Covington','Kentucky',40956);
INSERT INTO [City](Name,State,Population) VALUES ('Rockwall','Texas',40922);
INSERT INTO [City](Name,State,Population) VALUES ('Meridian','Mississippi',40921);
INSERT INTO [City](Name,State,Population) VALUES ('Riverton','Utah',40921);
INSERT INTO [City](Name,State,Population) VALUES ('St. Cloud','Florida',40918);
INSERT INTO [City](Name,State,Population) VALUES ('Quincy','Illinois',40915);
INSERT INTO [City](Name,State,Population) VALUES ('Morgan Hill','California',40836);
INSERT INTO [City](Name,State,Population) VALUES ('Warren','Ohio',40768);
INSERT INTO [City](Name,State,Population) VALUES ('Edmonds','Washington',40727);
INSERT INTO [City](Name,State,Population) VALUES ('Burleson','Texas',40714);
INSERT INTO [City](Name,State,Population) VALUES ('Beverly','Massachusetts',40664);
INSERT INTO [City](Name,State,Population) VALUES ('Mankato','Minnesota',40641);
INSERT INTO [City](Name,State,Population) VALUES ('Hagerstown','Maryland',40612);
INSERT INTO [City](Name,State,Population) VALUES ('Prescott','Arizona',40590);
INSERT INTO [City](Name,State,Population) VALUES ('Campbell','California',40584);
INSERT INTO [City](Name,State,Population) VALUES ('Cedar Falls','Iowa',40566);
INSERT INTO [City](Name,State,Population) VALUES ('Beaumont','California',40481);
INSERT INTO [City](Name,State,Population) VALUES ('La Puente','California',40435);
INSERT INTO [City](Name,State,Population) VALUES ('Crystal Lake','Illinois',40388);
INSERT INTO [City](Name,State,Population) VALUES ('Fitchburg','Massachusetts',40383);
INSERT INTO [City](Name,State,Population) VALUES ('Carol Stream','Illinois',40379);
INSERT INTO [City](Name,State,Population) VALUES ('Hickory','North Carolina',40361);
INSERT INTO [City](Name,State,Population) VALUES ('Streamwood','Illinois',40351);
INSERT INTO [City](Name,State,Population) VALUES ('Norwich','Connecticut',40347);
INSERT INTO [City](Name,State,Population) VALUES ('Coppell','Texas',40342);
INSERT INTO [City](Name,State,Population) VALUES ('San Gabriel','California',40275);
INSERT INTO [City](Name,State,Population) VALUES ('Holyoke','Massachusetts',40249);
INSERT INTO [City](Name,State,Population) VALUES ('Bentonville','Arkansas',40167);
INSERT INTO [City](Name,State,Population) VALUES ('Florence','Alabama',40059);
INSERT INTO [City](Name,State,Population) VALUES ('Peachtree Corners','Georgia',40059);
INSERT INTO [City](Name,State,Population) VALUES ('Brentwood','Tennessee',40021);
INSERT INTO [City](Name,State,Population) VALUES ('Bozeman','Montana',39860);
INSERT INTO [City](Name,State,Population) VALUES ('New Berlin','Wisconsin',39834);
INSERT INTO [City](Name,State,Population) VALUES ('Goose Creek','South Carolina',39823);
INSERT INTO [City](Name,State,Population) VALUES ('Huntsville','Texas',39795);
INSERT INTO [City](Name,State,Population) VALUES ('Prescott Valley','Arizona',39791);
INSERT INTO [City](Name,State,Population) VALUES ('Maplewood','Minnesota',39765);
INSERT INTO [City](Name,State,Population) VALUES ('Romeoville','Illinois',39650);
INSERT INTO [City](Name,State,Population) VALUES ('Duncanville','Texas',39605);
INSERT INTO [City](Name,State,Population) VALUES ('Atlantic City','New Jersey',39551);
INSERT INTO [City](Name,State,Population) VALUES ('Clovis','New Mexico',39508);
INSERT INTO [City](Name,State,Population) VALUES ('The Colony','Texas',39458);
INSERT INTO [City](Name,State,Population) VALUES ('Culver City','California',39428);
INSERT INTO [City](Name,State,Population) VALUES ('Marlborough','Massachusetts',39414);
INSERT INTO [City](Name,State,Population) VALUES ('Hilton Head Island','South Carolina',39412);
INSERT INTO [City](Name,State,Population) VALUES ('Moorhead','Minnesota',39398);
INSERT INTO [City](Name,State,Population) VALUES ('Calexico','California',39389);
INSERT INTO [City](Name,State,Population) VALUES ('Bullhead City','Arizona',39383);
INSERT INTO [City](Name,State,Population) VALUES ('Germantown','Tennessee',39375);
INSERT INTO [City](Name,State,Population) VALUES ('La Quinta','California',39331);
INSERT INTO [City](Name,State,Population) VALUES ('Lancaster','Ohio',39325);
INSERT INTO [City](Name,State,Population) VALUES ('Wausau','Wisconsin',39309);
INSERT INTO [City](Name,State,Population) VALUES ('Sherman','Texas',39296);
INSERT INTO [City](Name,State,Population) VALUES ('Ocoee','Florida',39172);
INSERT INTO [City](Name,State,Population) VALUES ('Shakopee','Minnesota',39167);
INSERT INTO [City](Name,State,Population) VALUES ('Woburn','Massachusetts',39083);
INSERT INTO [City](Name,State,Population) VALUES ('Bremerton','Washington',39056);
INSERT INTO [City](Name,State,Population) VALUES ('Rock Island','Illinois',38877);
INSERT INTO [City](Name,State,Population) VALUES ('Muskogee','Oklahoma',38863);
INSERT INTO [City](Name,State,Population) VALUES ('Cape Girardeau','Missouri',38816);
INSERT INTO [City](Name,State,Population) VALUES ('Annapolis','Maryland',38722);
INSERT INTO [City](Name,State,Population) VALUES ('Greenacres','Florida',38696);
INSERT INTO [City](Name,State,Population) VALUES ('Ormond Beach','Florida',38661);
INSERT INTO [City](Name,State,Population) VALUES ('Hallandale Beach','Florida',38632);
INSERT INTO [City](Name,State,Population) VALUES ('Stanton','California',38623);
INSERT INTO [City](Name,State,Population) VALUES ('Puyallup','Washington',38609);
INSERT INTO [City](Name,State,Population) VALUES ('Pacifica','California',38606);
INSERT INTO [City](Name,State,Population) VALUES ('Hanover Park','Illinois',38510);
INSERT INTO [City](Name,State,Population) VALUES ('Hurst','Texas',38448);
INSERT INTO [City](Name,State,Population) VALUES ('Lima','Ohio',38355);
INSERT INTO [City](Name,State,Population) VALUES ('Marana','Arizona',38290);
INSERT INTO [City](Name,State,Population) VALUES ('Carpentersville','Illinois',38241);
INSERT INTO [City](Name,State,Population) VALUES ('Oakley','California',38194);
INSERT INTO [City](Name,State,Population) VALUES ('Huber Heights','Ohio',38142);
INSERT INTO [City](Name,State,Population) VALUES ('Lancaster','Texas',38071);
INSERT INTO [City](Name,State,Population) VALUES ('Montclair','California',38027);
INSERT INTO [City](Name,State,Population) VALUES ('Wheeling','Illinois',38015);
INSERT INTO [City](Name,State,Population) VALUES ('Brookfield','Wisconsin',37999);
INSERT INTO [City](Name,State,Population) VALUES ('Park Ridge','Illinois',37839);
INSERT INTO [City](Name,State,Population) VALUES ('Florence','South Carolina',37792);
INSERT INTO [City](Name,State,Population) VALUES ('Roy','Utah',37733);
INSERT INTO [City](Name,State,Population) VALUES ('Winter Garden','Florida',37711);
INSERT INTO [City](Name,State,Population) VALUES ('Chelsea','Massachusetts',37670);
INSERT INTO [City](Name,State,Population) VALUES ('Valley Stream','New York',37659);
INSERT INTO [City](Name,State,Population) VALUES ('Spartanburg','South Carolina',37647);
INSERT INTO [City](Name,State,Population) VALUES ('Lake Oswego','Oregon',37610);
INSERT INTO [City](Name,State,Population) VALUES ('Friendswood','Texas',37587);
INSERT INTO [City](Name,State,Population) VALUES ('Westerville','Ohio',37530);
INSERT INTO [City](Name,State,Population) VALUES ('Northglenn','Colorado',37499);
INSERT INTO [City](Name,State,Population) VALUES ('Phenix City','Alabama',37498);
INSERT INTO [City](Name,State,Population) VALUES ('Grove City','Ohio',37490);
INSERT INTO [City](Name,State,Population) VALUES ('Texarkana','Texas',37442);
INSERT INTO [City](Name,State,Population) VALUES ('Addison','Illinois',37385);
INSERT INTO [City](Name,State,Population) VALUES ('Dover','Delaware',37366);
INSERT INTO [City](Name,State,Population) VALUES ('Lincoln Park','Michigan',37313);
INSERT INTO [City](Name,State,Population) VALUES ('Calumet City','Illinois',37240);
INSERT INTO [City](Name,State,Population) VALUES ('Muskegon','Michigan',37213);
INSERT INTO [City](Name,State,Population) VALUES ('Aventura','Florida',37199);
INSERT INTO [City](Name,State,Population) VALUES ('Martinez','California',37165);
INSERT INTO [City](Name,State,Population) VALUES ('Greenfield','Wisconsin',37159);
INSERT INTO [City](Name,State,Population) VALUES ('Apache Junction','Arizona',37130);
INSERT INTO [City](Name,State,Population) VALUES ('Monrovia','California',37101);
INSERT INTO [City](Name,State,Population) VALUES ('Weslaco','Texas',37093);
INSERT INTO [City](Name,State,Population) VALUES ('Keizer','Oregon',37064);
INSERT INTO [City](Name,State,Population) VALUES ('Spanish Fork','Utah',36956);
INSERT INTO [City](Name,State,Population) VALUES ('Beloit','Wisconsin',36888);
INSERT INTO [City](Name,State,Population) VALUES ('Panama City','Florida',36877);
END


UPDATE [City] SET [State] = s.Abbr
FROM [City] c inner join [State] s on c.[State] = s.Name
GO
