//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Gravitybox.GeoLocation.EFDAL;
using Gravitybox.GeoLocation.EFDAL.EventArguments;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data.Linq;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;

namespace Gravitybox.GeoLocation.EFDAL.Entity
{
	/// <summary>
	/// The 'CanadaPostalCode' entity
	/// </summary>
	[DataContract]
	[Serializable]
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	[FieldNameConstants(typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))]
	[System.ComponentModel.DataAnnotations.MetadataType(typeof(Gravitybox.GeoLocation.EFDAL.Entity.Metadata.CanadaPostalCodeMetadata))]
	[EntityMetadata("CanadaPostalCode", false, false, false, false, "", true, false, false, "dbo")]
	public partial class CanadaPostalCode : BaseEntity, Gravitybox.GeoLocation.EFDAL.IBusinessObject, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging, System.ICloneable, Gravitybox.GeoLocation.EFDAL.ICreatable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'CanadaPostalCode' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'City' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'City' property")]
			City,
			/// <summary>
			/// Field mapping for the 'Latitude' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Latitude' property")]
			Latitude,
			/// <summary>
			/// Field mapping for the 'Longitude' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Longitude' property")]
			Longitude,
			/// <summary>
			/// Field mapping for the 'PostalCode' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'PostalCode' property")]
			PostalCode,
			/// <summary>
			/// Field mapping for the 'RowId' property
			/// </summary>
			[System.ComponentModel.DataAnnotations.Key]
			[System.ComponentModel.ReadOnly(true)]
			[System.ComponentModel.Description("Field mapping for the 'RowId' property")]
			RowId,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode class
		/// </summary>
		public CanadaPostalCode()
		{

		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'CanadaPostalCode.City' field.
		/// </summary>
		/// <remarks>Field: [CanadaPostalCode].[City], Field Length: 100, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("City")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string City
		{
			get { return _city; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "CanadaPostalCode.City", GetMaxLength(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City)));
				if (value == _city) return;
				var eventArg = new Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string>(value, "City");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_city = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("City"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'CanadaPostalCode.Latitude' field.
		/// </summary>
		/// <remarks>Field: [CanadaPostalCode].[Latitude], Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Latitude")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual double? Latitude
		{
			get { return _latitude; }
			set
			{
				if (value == _latitude) return;
				var eventArg = new Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?>(value, "Latitude");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_latitude = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Latitude"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'CanadaPostalCode.Longitude' field.
		/// </summary>
		/// <remarks>Field: [CanadaPostalCode].[Longitude], Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Longitude")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual double? Longitude
		{
			get { return _longitude; }
			set
			{
				if (value == _longitude) return;
				var eventArg = new Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?>(value, "Longitude");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_longitude = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Longitude"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'CanadaPostalCode.PostalCode' field.
		/// </summary>
		/// <remarks>Field: [CanadaPostalCode].[PostalCode], Field Length: 10, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("PostalCode")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string PostalCode
		{
			get { return _postalCode; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "CanadaPostalCode.PostalCode", GetMaxLength(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode)));
				if (value == _postalCode) return;
				var eventArg = new Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string>(value, "PostalCode");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_postalCode = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("PostalCode"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'CanadaPostalCode.RowId' field.
		/// </summary>
		/// <remarks>Field: [CanadaPostalCode].[RowId], Not Nullable, Primary Key, AutoNumber, Unique, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("RowId")]
		[System.ComponentModel.DataAnnotations.Schema.Index(IsUnique = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual int RowId
		{
			get { return _rowId; }
			protected internal set
			{
				if (value == _rowId) return;
				var eventArg = new Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<int>(value, "RowId");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_rowId = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("RowId"));
			}
		}

		#endregion

		#region Property Holders

		/// <summary />
		protected string _city;
		/// <summary>
		/// Occurs when the 'City' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string>> CityChanging;

		/// <summary>
		/// Raises the OnCityChanging event.
		/// </summary>
		protected virtual void OnCityChanging(Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CityChanging != null)
				this.CityChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'City' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CityChanged;

		/// <summary>
		/// Raises the OnCityChanged event.
		/// </summary>
		protected virtual void OnCityChanged(ChangedEventArgs<string> e)
		{
			if (this.CityChanged != null)
				this.CityChanged(this, e);
		}

		/// <summary />
		protected double? _latitude;
		/// <summary>
		/// Occurs when the 'Latitude' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?>> LatitudeChanging;

		/// <summary>
		/// Raises the OnLatitudeChanging event.
		/// </summary>
		protected virtual void OnLatitudeChanging(Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?> e)
		{
			if (this.LatitudeChanging != null)
				this.LatitudeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Latitude' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<double?>> LatitudeChanged;

		/// <summary>
		/// Raises the OnLatitudeChanged event.
		/// </summary>
		protected virtual void OnLatitudeChanged(ChangedEventArgs<double?> e)
		{
			if (this.LatitudeChanged != null)
				this.LatitudeChanged(this, e);
		}

		/// <summary />
		protected double? _longitude;
		/// <summary>
		/// Occurs when the 'Longitude' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?>> LongitudeChanging;

		/// <summary>
		/// Raises the OnLongitudeChanging event.
		/// </summary>
		protected virtual void OnLongitudeChanging(Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<double?> e)
		{
			if (this.LongitudeChanging != null)
				this.LongitudeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Longitude' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<double?>> LongitudeChanged;

		/// <summary>
		/// Raises the OnLongitudeChanged event.
		/// </summary>
		protected virtual void OnLongitudeChanged(ChangedEventArgs<double?> e)
		{
			if (this.LongitudeChanged != null)
				this.LongitudeChanged(this, e);
		}

		/// <summary />
		protected string _postalCode;
		/// <summary>
		/// Occurs when the 'PostalCode' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string>> PostalCodeChanging;

		/// <summary>
		/// Raises the OnPostalCodeChanging event.
		/// </summary>
		protected virtual void OnPostalCodeChanging(Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.PostalCodeChanging != null)
				this.PostalCodeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'PostalCode' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> PostalCodeChanged;

		/// <summary>
		/// Raises the OnPostalCodeChanged event.
		/// </summary>
		protected virtual void OnPostalCodeChanged(ChangedEventArgs<string> e)
		{
			if (this.PostalCodeChanged != null)
				this.PostalCodeChanged(this, e);
		}

		/// <summary />
		protected int _rowId;
		/// <summary>
		/// Occurs when the 'RowId' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<int>> RowIdChanging;

		/// <summary>
		/// Raises the OnRowIdChanging event.
		/// </summary>
		protected virtual void OnRowIdChanging(Gravitybox.GeoLocation.EFDAL.EventArguments.ChangingEventArgs<int> e)
		{
			if (this.RowIdChanging != null)
				this.RowIdChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'RowId' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<int>> RowIdChanged;

		/// <summary>
		/// Raises the OnRowIdChanged event.
		/// </summary>
		protected virtual void OnRowIdChanged(ChangedEventArgs<int> e)
		{
			if (this.RowIdChanged != null)
				this.RowIdChanged(this, e);
		}


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field)
		{
			switch (field)
			{
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City:
					return 100;
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Latitude:
					return 0;
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Longitude:
					return 0;
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode:
					return 10;
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.RowId:
					return 0;
			}
			return 0;
		}

		int Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field)
		{
			if (field.GetType() != typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants'.");

			switch ((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field)
			{
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City: return typeof(string);
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Latitude: return typeof(double?);
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Longitude: return typeof(double?);
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode: return typeof(string);
				case Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.RowId: return typeof(int);
			}
			return null;
		}

		System.Type Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants'.");

			return GetFieldType((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants'.");
			return this.GetValue((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field, defaultValue);
		}

		void Gravitybox.GeoLocation.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants'.");
			this.SetValue((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field, newValue);
		}

		void Gravitybox.GeoLocation.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue, bool fixLength)
		{
			if (field.GetType() != typeof(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants'.");
			this.SetValue((Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants)field, newValue, fixLength);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Generic primary key for this object
		/// </summary>
		Gravitybox.GeoLocation.EFDAL.IPrimaryKey Gravitybox.GeoLocation.EFDAL.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return new PrimaryKey(Util.HashPK("CanadaPostalCode", this.RowId)); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.Clone(this);
			item._rowId = 0;
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static CanadaPostalCode Clone(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode item)
		{
			var newItem = new CanadaPostalCode();
			newItem.City = item.City;
			newItem.Latitude = item.Latitude;
			newItem.Longitude = item.Longitude;
			newItem.PostalCode = item.PostalCode;
			newItem.RowId = item.RowId;
			return newItem;
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field, object defaultValue)
		{
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City)
				return this.City;
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Latitude)
				return ((this.Latitude == null) ? defaultValue : this.Latitude);
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Longitude)
				return ((this.Longitude == null) ? defaultValue : this.Longitude);
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode)
				return this.PostalCode;
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.RowId)
				return this.RowId;
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.City)
			{
				this.City = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Latitude)
			{
				this.Latitude = GlobalValues.SetValueHelperDoubleNullableInternal(newValue);
			}
			else if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.Longitude)
			{
				this.Longitude = GlobalValues.SetValueHelperDoubleNullableInternal(newValue);
			}
			else if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.PostalCode)
			{
				this.PostalCode = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants.RowId)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		#endregion

		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "city": return "city";
				case "latitude": return "latitude";
				case "longitude": return "longitude";
				case "postalcode": return "postalcode";
				case "rowid": return "rowid";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "city": return "CanadaPostalCode";
				case "latitude": return "CanadaPostalCode";
				case "longitude": return "CanadaPostalCode";
				case "postalcode": return "CanadaPostalCode";
				case "rowid": return "CanadaPostalCode";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "city": return "CanadaPostalCode";
				case "latitude": return "CanadaPostalCode";
				case "longitude": return "CanadaPostalCode";
				case "postalcode": return "CanadaPostalCode";
				case "rowid": return "CanadaPostalCode";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[city\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "CanadaPostalCode") + "].[city]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[latitude\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "CanadaPostalCode") + "].[latitude]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[longitude\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "CanadaPostalCode") + "].[longitude]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[postalcode\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "CanadaPostalCode") + "].[postalcode]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[rowid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "CanadaPostalCode") + "].[rowid]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion

		#region DeleteData

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: Gravitybox.GeoLocation.EFDAL.GeoLocationEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, QueryOptimizer optimizer)
		{
			return DeleteData(where: where, optimizer: optimizer, startup: new ContextStartup(null), connectionString: Gravitybox.GeoLocation.EFDAL.GeoLocationEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, string connectionString)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: connectionString);
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <param name="startup">The startup options</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, QueryOptimizer optimizer, ContextStartup startup, string connectionString)
		{
			if (optimizer == null)
				optimizer = new QueryOptimizer();
				if (startup == null) startup = new ContextStartup(null);

			using (var connection = Gravitybox.GeoLocation.EFDAL.DBHelper.GetConnection(Gravitybox.GeoLocation.EFDAL.Util.StripEFCS2Normal(connectionString)))
			{
				using (var dc = new DataContext(connection))
				{
					var template = dc.GetTable<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery>();
					using (var cmd = BusinessEntityQuery.GetCommand<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery>(dc, template, where))
					{
						if (!startup.DefaultTimeout && startup.CommandTimeout > 0) cmd.CommandTimeout = startup.CommandTimeout;
						else
						{
							var cb = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
							cmd.CommandTimeout = cb.ConnectTimeout;
						}

						var parser = LinqSQLParser.Create(cmd.CommandText, LinqSQLParser.ObjectTypeConstants.Table);
						var sql = "CREATE TABLE #t ([RowId] [Int])";
						sql += "set rowcount " + optimizer.ChunkSize + ";";
						sql += "INSERT INTO #t ([RowId])";
						sql += "SELECT [t0].[RowId] #t\r\n";
						sql += parser.GetFromClause(optimizer) + "\r\n";
						sql += parser.GetWhereClause();
						sql += "\r\n";

						var noLock = string.Empty;
						noLock = (optimizer.NoLocking ? "WITH (READUNCOMMITTED) " : string.Empty);
						sql += "DELETE [CanadaPostalCode] FROM [dbo].[CanadaPostalCode] " + noLock + "INNER JOIN #t ON [dbo].[CanadaPostalCode].[RowId] = #t.[RowId]\r\n";
						sql += ";select @@rowcount";
						sql = "set ansi_nulls off;" + sql + ";drop table #t;";
						cmd.CommandText = sql;
						dc.Connection.Open();
						var startTime = DateTime.Now;
						var affected = 0;
						var count = 0;
						do
						{
							count = (int)cmd.ExecuteScalar();
							affected += count;
						} while (count > 0 && optimizer.ChunkSize > 0);
						var endTime = DateTime.Now;
						optimizer.TotalMilliseconds = (long)endTime.Subtract(startTime).TotalMilliseconds;
						dc.Connection.Close();
						return affected;
					}
				}
			}
		}

		#endregion

		#region UpdateData

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, TSource newValue)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, TSource newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false, startup: null, connection: connection, transaction: transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="startup">A configuration object</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, TSource newValue, ContextStartup startup, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false, startup: startup, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, TSource newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode newValue)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>> select, Expression<Func<Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, bool>> where, Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode, Gravitybox.GeoLocation.EFDAL.CanadaPostalCodeQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "CanadaPostalCode", getField: GetDatabaseFieldName, hasModifyAudit: false, connectionString: connectionString);
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "City": return "City";
				case "Latitude": return "Latitude";
				case "Longitude": return "Longitude";
				case "PostalCode": return "PostalCode";
				case "RowId": return "RowId";
			}
			return string.Empty;
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'CanadaPostalCode' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Gravitybox.GeoLocation.EFDAL.Entity.CanadaPostalCode;
			if (other == null) return false;
			return (
				other.City == this.City &&
				other.Latitude == this.Latitude &&
				other.Longitude == this.Longitude &&
				other.PostalCode == this.PostalCode &&
				other.RowId == this.RowId
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

	}
}

#region Metadata Class

namespace Gravitybox.GeoLocation.EFDAL.Entity.Metadata
{
	/// <summary>
	/// Metadata class for the 'CanadaPostalCode' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	public partial class CanadaPostalCodeMetadata : Gravitybox.GeoLocation.EFDAL.IMetadata
	{
		#region Properties

		/// <summary>
		/// Metadata information for the 'City' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'City' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'City' has a maximum length of 100")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "City", AutoGenerateField = true)]
		public object City;

		/// <summary>
		/// Metadata information for the 'Latitude' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Latitude", AutoGenerateField = true)]
		public object Latitude;

		/// <summary>
		/// Metadata information for the 'Longitude' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Longitude", AutoGenerateField = true)]
		public object Longitude;

		/// <summary>
		/// Metadata information for the 'PostalCode' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'PostalCode' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(10, ErrorMessage = "The property 'PostalCode' has a maximum length of 10")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "PostalCode", AutoGenerateField = true)]
		public object PostalCode;

		/// <summary>
		/// Metadata information for the 'RowId' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'RowId' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.ReadOnly(true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "RowId", AutoGenerateField = true)]
		public object RowId;

		#endregion

		#region Methods
		/// <summary>
		/// Gets the underlying table name.
		/// </summary>
		public virtual string GetTableName()
		{
			return "CanadaPostalCode";
		}

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		public virtual List<string> GetFields()
		{
			var retval = new List<string>();
			retval.Add("City");
			retval.Add("Latitude");
			retval.Add("Longitude");
			retval.Add("PostalCode");
			retval.Add("RowId");
			return retval;
		}

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		public virtual System.Type InheritsFrom()
		{
			return null;
		}

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		public virtual string Schema()
		{
			return "dbo";
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		public virtual string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "City": return "City";
				case "Latitude": return "Latitude";
				case "Longitude": return "Longitude";
				case "PostalCode": return "PostalCode";
				case "RowId": return "RowId";
			}
			return string.Empty;
		}

		#endregion

	}

}

#endregion

#pragma warning restore 612

