//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 0168
#pragma warning disable 0108
using System;
using System.Linq;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using Gravitybox.LocationService.EFDAL.Entity;

namespace Gravitybox.LocationService.EFDAL
{
	#region Entity Context

	/// <summary />
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	public partial interface ILocationServiceEntities : System.IDisposable
	{
		/// <summary />
		event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.EntityListEventArgs> BeforeSaveAddedEntity;
		/// <summary />
		event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.EntityListEventArgs> BeforeSaveModifiedEntity;
		/// <summary />
		int SaveChanges();

		/// <summary />
		IQueryable<Gravitybox.LocationService.EFDAL.Entity.State> State { get ; }

		/// <summary />
		IQueryable<Gravitybox.LocationService.EFDAL.Entity.Zip> Zip { get ; }

		/// <summary />
		Gravitybox.LocationService.EFDAL.IBusinessObject AddItem(Gravitybox.LocationService.EFDAL.IBusinessObject entity);

		/// <summary />
		void DeleteItem(Gravitybox.LocationService.EFDAL.IBusinessObject entity);

		/// <summary />
		void ReloadItem(BaseEntity entity);

		/// <summary />
		void DetachItem(BaseEntity entity);

		/// <summary />
		ContextStartup ContextStartup { get; }

		/// <summary />
		System.Guid InstanceKey { get; }
	}

	#endregion

	/// <summary />
	public partial interface IMetadata
	{
		/// <summary>
		/// Gets the underlying table name.
		/// </summary>
		string GetTableName();

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		List<string> GetFields();

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		System.Type InheritsFrom();

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		string Schema();

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		string GetDatabaseFieldName(string field);
	}

}

#pragma warning restore 0168
#pragma warning restore 0108
