//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Gravitybox.LocationService.EFDAL;
using Gravitybox.LocationService.EFDAL.EventArguments;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data.Linq;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;

namespace Gravitybox.LocationService.EFDAL.Entity
{
	/// <summary>
	/// The 'Zip' entity
	/// </summary>
	[DataContract]
	[Serializable]
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	[FieldNameConstants(typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))]
	[System.ComponentModel.DataAnnotations.MetadataType(typeof(Gravitybox.LocationService.EFDAL.Entity.Metadata.ZipMetadata))]
	[EntityMetadata("Zip", false, true, true, true, "", true, false, false, "dbo")]
	public partial class Zip : BaseEntity, Gravitybox.LocationService.EFDAL.IBusinessObject, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging, System.ICloneable, Gravitybox.LocationService.EFDAL.IAuditable, Gravitybox.LocationService.EFDAL.IAuditableSet, Gravitybox.LocationService.EFDAL.ICreatable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'Zip' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'City' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'City' property")]
			City,
			/// <summary>
			/// Field mapping for the 'Latitude' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Latitude' property")]
			Latitude,
			/// <summary>
			/// Field mapping for the 'Longitude' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Longitude' property")]
			Longitude,
			/// <summary>
			/// Field mapping for the 'Name' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Name' property")]
			Name,
			/// <summary>
			/// Field mapping for the 'Population' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Population' property")]
			Population,
			/// <summary>
			/// Field mapping for the 'State' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'State' property")]
			State,
			/// <summary>
			/// Field mapping for the 'ZipId' property
			/// </summary>
			[System.ComponentModel.DataAnnotations.Key]
			[System.ComponentModel.ReadOnly(true)]
			[System.ComponentModel.Description("Field mapping for the 'ZipId' property")]
			ZipId,
			/// <summary>
			/// Field mapping for the 'CreatedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedBy' property")]
			CreatedBy,
			/// <summary>
			/// Field mapping for the 'CreatedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedDate' property")]
			CreatedDate,
			/// <summary>
			/// Field mapping for the 'ModifiedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedBy' property")]
			ModifiedBy,
			/// <summary>
			/// Field mapping for the 'ModifiedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedDate' property")]
			ModifiedDate,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the Gravitybox.LocationService.EFDAL.Entity.Zip class
		/// </summary>
		public Zip()
		{

		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'Zip.City' field.
		/// </summary>
		/// <remarks>Field: [Zip].[City], Field Length: 50, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("City")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string City
		{
			get { return _city; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Zip.City", GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City)));
				if (value == _city) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>(value, "City");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_city = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("City"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.Latitude' field.
		/// </summary>
		/// <remarks>Field: [Zip].[Latitude], Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Latitude")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual double? Latitude
		{
			get { return _latitude; }
			set
			{
				if (value == _latitude) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?>(value, "Latitude");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_latitude = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Latitude"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.Longitude' field.
		/// </summary>
		/// <remarks>Field: [Zip].[Longitude], Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Longitude")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual double? Longitude
		{
			get { return _longitude; }
			set
			{
				if (value == _longitude) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?>(value, "Longitude");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_longitude = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Longitude"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.Name' field.
		/// </summary>
		/// <remarks>Field: [Zip].[Name], Field Length: 10, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Name")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string Name
		{
			get { return _name; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Zip.Name", GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name)));
				if (value == _name) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>(value, "Name");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_name = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Name"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.Population' field.
		/// </summary>
		/// <remarks>Field: [Zip].[Population], Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Population")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual int? Population
		{
			get { return _population; }
			set
			{
				if (value == _population) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int?>(value, "Population");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_population = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Population"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.State' field.
		/// </summary>
		/// <remarks>Field: [Zip].[State], Field Length: 50, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("State")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string State
		{
			get { return _state; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Zip.State", GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State)));
				if (value == _state) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>(value, "State");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_state = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("State"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Zip.ZipId' field.
		/// </summary>
		/// <remarks>Field: [Zip].[ZipId], Not Nullable, Primary Key, AutoNumber, Unique, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("ZipId")]
		[System.ComponentModel.DataAnnotations.Schema.Index(IsUnique = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual int ZipId
		{
			get { return _zipId; }
			protected internal set
			{
				if (value == _zipId) return;
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int>(value, "ZipId");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_zipId = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ZipId"));
			}
		}

		/// <summary>
		/// The audit field for the 'Created By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string CreatedBy
		{
			get { return _createdby; }
			protected internal set
			{
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>(value, "CreatedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createdby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedBy"));
			}
		}

		/// <summary />
		protected string _createdby;

		/// <summary>
		/// The audit field for the 'Created Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? CreatedDate
		{
			get { return _createddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "CreatedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedDate"));
			}
		}

		/// <summary />
		protected DateTime? _createddate;

		/// <summary>
		/// The audit field for the 'Modified By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string ModifiedBy
		{
			get { return _modifiedby; }
			protected internal set
			{
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>(value, "ModifiedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifiedby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedBy"));
			}
		}

		/// <summary />
		protected string _modifiedby;

		/// <summary>
		/// The audit field for the 'Modified Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? ModifiedDate
		{
			get { return _modifieddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "ModifiedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifieddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedDate"));
			}
		}

		/// <summary />
		protected DateTime? _modifieddate;

		/// <summary>
		/// The audit field for the 'Timestamp' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual byte[] TimeStamp
		{
			get { return _timestamp; }
			protected internal set
			{
				var eventArg = new Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<byte[]>(value, "TimeStamp");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_timestamp = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("TimeStamp"));
			}
		}

		/// <summary />
		protected byte[] _timestamp;

		#endregion

		#region Property Holders

		/// <summary />
		protected string _city;
		/// <summary>
		/// Occurs when the 'City' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>> CityChanging;

		/// <summary>
		/// Raises the OnCityChanging event.
		/// </summary>
		protected virtual void OnCityChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CityChanging != null)
				this.CityChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'City' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CityChanged;

		/// <summary>
		/// Raises the OnCityChanged event.
		/// </summary>
		protected virtual void OnCityChanged(ChangedEventArgs<string> e)
		{
			if (this.CityChanged != null)
				this.CityChanged(this, e);
		}

		/// <summary />
		protected double? _latitude;
		/// <summary>
		/// Occurs when the 'Latitude' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?>> LatitudeChanging;

		/// <summary>
		/// Raises the OnLatitudeChanging event.
		/// </summary>
		protected virtual void OnLatitudeChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?> e)
		{
			if (this.LatitudeChanging != null)
				this.LatitudeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Latitude' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<double?>> LatitudeChanged;

		/// <summary>
		/// Raises the OnLatitudeChanged event.
		/// </summary>
		protected virtual void OnLatitudeChanged(ChangedEventArgs<double?> e)
		{
			if (this.LatitudeChanged != null)
				this.LatitudeChanged(this, e);
		}

		/// <summary />
		protected double? _longitude;
		/// <summary>
		/// Occurs when the 'Longitude' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?>> LongitudeChanging;

		/// <summary>
		/// Raises the OnLongitudeChanging event.
		/// </summary>
		protected virtual void OnLongitudeChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<double?> e)
		{
			if (this.LongitudeChanging != null)
				this.LongitudeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Longitude' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<double?>> LongitudeChanged;

		/// <summary>
		/// Raises the OnLongitudeChanged event.
		/// </summary>
		protected virtual void OnLongitudeChanged(ChangedEventArgs<double?> e)
		{
			if (this.LongitudeChanged != null)
				this.LongitudeChanged(this, e);
		}

		/// <summary />
		protected string _name;
		/// <summary>
		/// Occurs when the 'Name' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>> NameChanging;

		/// <summary>
		/// Raises the OnNameChanging event.
		/// </summary>
		protected virtual void OnNameChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.NameChanging != null)
				this.NameChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Name' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> NameChanged;

		/// <summary>
		/// Raises the OnNameChanged event.
		/// </summary>
		protected virtual void OnNameChanged(ChangedEventArgs<string> e)
		{
			if (this.NameChanged != null)
				this.NameChanged(this, e);
		}

		/// <summary />
		protected int? _population;
		/// <summary>
		/// Occurs when the 'Population' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int?>> PopulationChanging;

		/// <summary>
		/// Raises the OnPopulationChanging event.
		/// </summary>
		protected virtual void OnPopulationChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int?> e)
		{
			if (this.PopulationChanging != null)
				this.PopulationChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Population' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<int?>> PopulationChanged;

		/// <summary>
		/// Raises the OnPopulationChanged event.
		/// </summary>
		protected virtual void OnPopulationChanged(ChangedEventArgs<int?> e)
		{
			if (this.PopulationChanged != null)
				this.PopulationChanged(this, e);
		}

		/// <summary />
		protected string _state;
		/// <summary>
		/// Occurs when the 'State' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>> StateChanging;

		/// <summary>
		/// Raises the OnStateChanging event.
		/// </summary>
		protected virtual void OnStateChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.StateChanging != null)
				this.StateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'State' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> StateChanged;

		/// <summary>
		/// Raises the OnStateChanged event.
		/// </summary>
		protected virtual void OnStateChanged(ChangedEventArgs<string> e)
		{
			if (this.StateChanged != null)
				this.StateChanged(this, e);
		}

		/// <summary />
		protected int _zipId;
		/// <summary>
		/// Occurs when the 'ZipId' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int>> ZipIdChanging;

		/// <summary>
		/// Raises the OnZipIdChanging event.
		/// </summary>
		protected virtual void OnZipIdChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<int> e)
		{
			if (this.ZipIdChanging != null)
				this.ZipIdChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ZipId' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<int>> ZipIdChanged;

		/// <summary>
		/// Raises the OnZipIdChanged event.
		/// </summary>
		protected virtual void OnZipIdChanged(ChangedEventArgs<int> e)
		{
			if (this.ZipIdChanged != null)
				this.ZipIdChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>> CreatedByChanging;

		/// <summary>
		/// Raises the OnCreatedByChanging event.
		/// </summary>
		protected virtual void OnCreatedByChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CreatedByChanging != null)
				this.CreatedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CreatedByChanged;

		/// <summary>
		/// Raises the OnCreatedByChanged event.
		/// </summary>
		protected virtual void OnCreatedByChanged(ChangedEventArgs<string> e)
		{
			if (this.CreatedByChanged != null)
				this.CreatedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> CreatedDateChanging;

		/// <summary>
		/// Raises the OnCreatedDateChanging event.
		/// </summary>
		protected virtual void OnCreatedDateChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanging != null)
				this.CreatedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> CreatedDateChanged;

		/// <summary>
		/// Raises the OnCreatedDateChanged event.
		/// </summary>
		protected virtual void OnCreatedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanged != null)
				this.CreatedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string>> ModifiedByChanging;

		/// <summary>
		/// Raises the OnModifiedByChanging event.
		/// </summary>
		protected virtual void OnModifiedByChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.ModifiedByChanging != null)
				this.ModifiedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> ModifiedByChanged;

		/// <summary>
		/// Raises the OnModifiedByChanged event.
		/// </summary>
		protected virtual void OnModifiedByChanged(ChangedEventArgs<string> e)
		{
			if (this.ModifiedByChanged != null)
				this.ModifiedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> ModifiedDateChanging;

		/// <summary>
		/// Raises the OnModifiedDateChanging event.
		/// </summary>
		protected virtual void OnModifiedDateChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanging != null)
				this.ModifiedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> ModifiedDateChanged;

		/// <summary>
		/// Raises the OnModifiedDateChanged event.
		/// </summary>
		protected virtual void OnModifiedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanged != null)
				this.ModifiedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'TimeStamp' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<byte[]>> TimeStampChanging;

		/// <summary>
		/// Raises the OnTimeStampChanging event.
		/// </summary>
		protected virtual void OnTimeStampChanging(Gravitybox.LocationService.EFDAL.EventArguments.ChangingEventArgs<byte[]> e)
		{
			if (this.TimeStampChanging != null)
				this.TimeStampChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'TimeStamp' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<byte[]>> TimeStampChanged;

		/// <summary>
		/// Raises the OnTimeStampChanged event.
		/// </summary>
		protected virtual void OnTimeStampChanged(ChangedEventArgs<byte[]> e)
		{
			if (this.TimeStampChanged != null)
				this.TimeStampChanged(this, e);
		}


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field)
		{
			switch (field)
			{
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City:
					return 50;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Latitude:
					return 0;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Longitude:
					return 0;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name:
					return 10;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Population:
					return 0;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State:
					return 50;
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ZipId:
					return 0;
			}
			return 0;
		}

		int Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field)
		{
			if (field.GetType() != typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants'.");

			switch ((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field)
			{
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City: return typeof(string);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Latitude: return typeof(double?);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Longitude: return typeof(double?);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name: return typeof(string);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Population: return typeof(int?);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State: return typeof(string);
				case Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ZipId: return typeof(int);
			}
			return null;
		}

		System.Type Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants'.");

			return GetFieldType((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants'.");
			return this.GetValue((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field, defaultValue);
		}

		void Gravitybox.LocationService.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants'.");
			this.SetValue((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field, newValue);
		}

		void Gravitybox.LocationService.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue, bool fixLength)
		{
			if (field.GetType() != typeof(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants'.");
			this.SetValue((Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants)field, newValue, fixLength);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Generic primary key for this object
		/// </summary>
		Gravitybox.LocationService.EFDAL.IPrimaryKey Gravitybox.LocationService.EFDAL.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return new PrimaryKey(Util.HashPK("Zip", this.ZipId)); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Gravitybox.LocationService.EFDAL.Entity.Zip.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Gravitybox.LocationService.EFDAL.Entity.Zip.Clone(this);
			item._zipId = 0;
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static Zip Clone(Gravitybox.LocationService.EFDAL.Entity.Zip item)
		{
			var newItem = new Zip();
			newItem.City = item.City;
			newItem.Latitude = item.Latitude;
			newItem.Longitude = item.Longitude;
			newItem.Name = item.Name;
			newItem.Population = item.Population;
			newItem.State = item.State;
			newItem.ZipId = item.ZipId;
			newItem.CreatedDate = item.CreatedDate;
			newItem.CreatedBy = item.CreatedBy;
			newItem.ModifiedDate = item.ModifiedDate;
			newItem.ModifiedBy = item.ModifiedBy;
			return newItem;
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field, object defaultValue)
		{
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City)
				return this.City;
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Latitude)
				return ((this.Latitude == null) ? defaultValue : this.Latitude);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Longitude)
				return ((this.Longitude == null) ? defaultValue : this.Longitude);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name)
				return this.Name;
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Population)
				return ((this.Population == null) ? defaultValue : this.Population);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State)
				return this.State;
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ZipId)
				return this.ZipId;
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.CreatedBy)
				return ((this.CreatedBy == null) ? defaultValue : this.CreatedBy);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.CreatedDate)
				return ((this.CreatedDate == null) ? defaultValue : this.CreatedDate);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ModifiedBy)
				return ((this.ModifiedBy == null) ? defaultValue : this.ModifiedBy);
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ModifiedDate)
				return ((this.ModifiedDate == null) ? defaultValue : this.ModifiedDate);
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.City)
			{
				this.City = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Latitude)
			{
				this.Latitude = GlobalValues.SetValueHelperDoubleNullableInternal(newValue);
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Longitude)
			{
				this.Longitude = GlobalValues.SetValueHelperDoubleNullableInternal(newValue);
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Name)
			{
				this.Name = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.Population)
			{
				this.Population = GlobalValues.SetValueHelperIntNullableInternal(newValue);
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.State)
			{
				this.State = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants.ZipId)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		#endregion

		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "city": return "city";
				case "latitude": return "latitude";
				case "longitude": return "longitude";
				case "name": return "name";
				case "population": return "population";
				case "state": return "state";
				case "zipid": return "zipid";
				case "createddate": return "createddate";
				case "createdby": return "createdby";
				case "modifieddate": return "modifieddate";
				case "modifiedby": return "modifiedby";
				case "timestamp": return "timestamp";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "city": return "Zip";
				case "latitude": return "Zip";
				case "longitude": return "Zip";
				case "name": return "Zip";
				case "population": return "Zip";
				case "state": return "Zip";
				case "zipid": return "Zip";
				case "createdby": return "Zip";
				case "createddate": return "Zip";
				case "modifiedby": return "Zip";
				case "modifieddate": return "Zip";
				case "timestamp": return "Zip";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "city": return "Zip";
				case "latitude": return "Zip";
				case "longitude": return "Zip";
				case "name": return "Zip";
				case "population": return "Zip";
				case "state": return "Zip";
				case "zipid": return "Zip";
				case "createdby": return "Zip";
				case "createddate": return "Zip";
				case "modifiedby": return "Zip";
				case "modifieddate": return "Zip";
				case "timestamp": return "Zip";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[city\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[city]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[latitude\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[latitude]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[longitude\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[longitude]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[name\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[name]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[population\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[population]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[state\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[state]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[zipid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[zipid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createdby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[createdby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[createddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifiedby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[modifiedby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifieddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[modifieddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[timestamp\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Zip") + "].[timestamp]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion

		#region DeleteData

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: Gravitybox.LocationService.EFDAL.LocationServiceEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, QueryOptimizer optimizer)
		{
			return DeleteData(where: where, optimizer: optimizer, startup: new ContextStartup(null), connectionString: Gravitybox.LocationService.EFDAL.LocationServiceEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, string connectionString)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: connectionString);
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <param name="startup">The startup options</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, QueryOptimizer optimizer, ContextStartup startup, string connectionString)
		{
			if (optimizer == null)
				optimizer = new QueryOptimizer();
				if (startup == null) startup = new ContextStartup(null);

			using (var connection = Gravitybox.LocationService.EFDAL.DBHelper.GetConnection(Gravitybox.LocationService.EFDAL.Util.StripEFCS2Normal(connectionString)))
			{
				using (var dc = new DataContext(connection))
				{
					var template = dc.GetTable<Gravitybox.LocationService.EFDAL.ZipQuery>();
					using (var cmd = BusinessEntityQuery.GetCommand<Gravitybox.LocationService.EFDAL.ZipQuery>(dc, template, where))
					{
						if (!startup.DefaultTimeout && startup.CommandTimeout > 0) cmd.CommandTimeout = startup.CommandTimeout;
						else
						{
							var cb = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
							cmd.CommandTimeout = cb.ConnectTimeout;
						}

						var parser = LinqSQLParser.Create(cmd.CommandText, LinqSQLParser.ObjectTypeConstants.Table);
						var sql = "CREATE TABLE #t ([ZipId] [Int])";
						sql += "set rowcount " + optimizer.ChunkSize + ";";
						sql += "INSERT INTO #t ([ZipId])";
						sql += "SELECT [t0].[ZipId] #t\r\n";
						sql += parser.GetFromClause(optimizer) + "\r\n";
						sql += parser.GetWhereClause();
						sql += "\r\n";

						var noLock = string.Empty;
						noLock = (optimizer.NoLocking ? "WITH (READUNCOMMITTED) " : string.Empty);
						sql += "DELETE [Zip] FROM [dbo].[Zip] " + noLock + "INNER JOIN #t ON [dbo].[Zip].[ZipId] = #t.[ZipId]\r\n";
						sql += ";select @@rowcount";
						sql = "set ansi_nulls off;" + sql + ";drop table #t;";
						cmd.CommandText = sql;
						dc.Connection.Open();
						var startTime = DateTime.Now;
						var affected = 0;
						var count = 0;
						do
						{
							count = (int)cmd.ExecuteScalar();
							affected += count;
						} while (count > 0 && optimizer.ChunkSize > 0);
						var endTime = DateTime.Now;
						optimizer.TotalMilliseconds = (long)endTime.Subtract(startTime).TotalMilliseconds;
						dc.Connection.Close();
						return affected;
					}
				}
			}
		}

		#endregion

		#region UpdateData

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, TSource newValue)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, TSource newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: null, connection: connection, transaction: transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="startup">A configuration object</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, TSource newValue, ContextStartup startup, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: startup, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, TSource newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, Gravitybox.LocationService.EFDAL.Entity.Zip newValue)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, TSource>> select, Expression<Func<Gravitybox.LocationService.EFDAL.ZipQuery, bool>> where, Gravitybox.LocationService.EFDAL.Entity.Zip newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.LocationService.EFDAL.Entity.Zip, Gravitybox.LocationService.EFDAL.ZipQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Zip", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(Gravitybox.LocationService.EFDAL.Entity.Zip.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "City": return "City";
				case "Latitude": return "Latitude";
				case "Longitude": return "Longitude";
				case "Name": return "Name";
				case "Population": return "Population";
				case "State": return "State";
				case "ZipId": return "ZipId";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "TimeStamp": return "TimeStamp";
			}
			return string.Empty;
		}

		#endregion

		#region Auditing
		string Gravitybox.LocationService.EFDAL.IAuditableSet.CreatedBy
		{
			get { return this.CreatedBy; }
			set { this.CreatedBy = value; }
		}

		string Gravitybox.LocationService.EFDAL.IAuditableSet.ModifiedBy
		{
			get { return this.ModifiedBy; }
			set { this.ModifiedBy = value; }
		}
		string Gravitybox.LocationService.EFDAL.IAuditable.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		System.DateTime? Gravitybox.LocationService.EFDAL.IAuditable.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		bool Gravitybox.LocationService.EFDAL.IAuditable.IsCreateAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.LocationService.EFDAL.IAuditable.IsModifyAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.LocationService.EFDAL.IAuditable.IsTimestampAuditImplemented
		{
			get { return true; }
		}

		string Gravitybox.LocationService.EFDAL.IAuditable.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		System.DateTime? Gravitybox.LocationService.EFDAL.IAuditable.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		byte[] Gravitybox.LocationService.EFDAL.IAuditable.TimeStamp
		{
			get { return this.TimeStamp; }
		}

		void IAuditableSet.ResetModifiedBy(string modifier)
		{
			if (this.ModifiedBy != modifier)
				this.ModifiedBy = modifier;
		}

		void IAuditableSet.ResetCreatedBy(string modifier)
		{
			if (this.CreatedBy != modifier)
				this.CreatedBy = modifier;
			((IAuditableSet)this).ResetModifiedBy(modifier);
		}

		System.DateTime? Gravitybox.LocationService.EFDAL.IAuditableSet.CreatedDate
		{
			get { return this.CreatedDate; }
			set { this.CreatedDate = value; }
		}

		System.DateTime? Gravitybox.LocationService.EFDAL.IAuditableSet.ModifiedDate
		{
			get { return this.ModifiedDate; }
			set { this.ModifiedDate = value; }
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'Zip' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Gravitybox.LocationService.EFDAL.Entity.Zip;
			if (other == null) return false;
			return (
				other.City == this.City &&
				other.Latitude == this.Latitude &&
				other.Longitude == this.Longitude &&
				other.Name == this.Name &&
				other.Population == this.Population &&
				other.State == this.State &&
				other.ZipId == this.ZipId
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

	}
}

#region Metadata Class

namespace Gravitybox.LocationService.EFDAL.Entity.Metadata
{
	/// <summary>
	/// Metadata class for the 'Zip' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	public partial class ZipMetadata : Gravitybox.LocationService.EFDAL.IMetadata
	{
		#region Properties

		/// <summary>
		/// Metadata information for the 'City' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'City' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(50, ErrorMessage = "The property 'City' has a maximum length of 50")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "City", AutoGenerateField = true)]
		public object City;

		/// <summary>
		/// Metadata information for the 'Latitude' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Latitude", AutoGenerateField = true)]
		public object Latitude;

		/// <summary>
		/// Metadata information for the 'Longitude' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Longitude", AutoGenerateField = true)]
		public object Longitude;

		/// <summary>
		/// Metadata information for the 'Name' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'Name' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(10, ErrorMessage = "The property 'Name' has a maximum length of 10")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Name", AutoGenerateField = true)]
		public object Name;

		/// <summary>
		/// Metadata information for the 'Population' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Population", AutoGenerateField = true)]
		public object Population;

		/// <summary>
		/// Metadata information for the 'State' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'State' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(50, ErrorMessage = "The property 'State' has a maximum length of 50")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "State", AutoGenerateField = true)]
		public object State;

		/// <summary>
		/// Metadata information for the 'ZipId' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'ZipId' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.ReadOnly(true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "ZipId", AutoGenerateField = true)]
		public object ZipId;

		/// <summary>
		/// Metadata information for the 'CreatedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'CreatedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedBy;

		/// <summary>
		/// Metadata information for the 'CreatedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedDate;

		/// <summary>
		/// Metadata information for the 'ModifiedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'ModifiedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedBy;

		/// <summary>
		/// Metadata information for the 'ModifiedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedDate;

		/// <summary>
		/// Metadata information for the 'TimeStamp' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Timestamp()]
		[System.ComponentModel.DataAnnotations.ConcurrencyCheck()]
		[System.ComponentModel.ReadOnly(true)]
		public object TimeStamp;

		#endregion

		#region Methods
		/// <summary>
		/// Gets the underlying table name.
		/// </summary>
		public virtual string GetTableName()
		{
			return "Zip";
		}

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		public virtual List<string> GetFields()
		{
			var retval = new List<string>();
			retval.Add("City");
			retval.Add("Latitude");
			retval.Add("Longitude");
			retval.Add("Name");
			retval.Add("Population");
			retval.Add("State");
			retval.Add("ZipId");
			return retval;
		}

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		public virtual System.Type InheritsFrom()
		{
			return null;
		}

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		public virtual string Schema()
		{
			return "dbo";
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		public virtual string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "City": return "City";
				case "Latitude": return "Latitude";
				case "Longitude": return "Longitude";
				case "Name": return "Name";
				case "Population": return "Population";
				case "State": return "State";
				case "ZipId": return "ZipId";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "TimeStamp": return "TimeStamp";
			}
			return string.Empty;
		}

		#endregion

	}

}

#endregion

#pragma warning restore 612

