//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 0168
#pragma warning disable 0108
using System;
using System.Linq;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using nHydrate.LocationService.EFDAL.Interfaces.Entity;

namespace nHydrate.LocationService.EFDAL.Interfaces
{
	#region Entity Context

	/// <summary>
	/// There are no comments for LocationServiceEntities in the schema.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "5.2.0")]
	public partial interface ILocationServiceEntities : System.IDisposable
	{
		/// <summary>
		/// There are no comments for State in the schema.
		/// </summary>
		IObjectSet<nHydrate.LocationService.EFDAL.Interfaces.Entity.IState> State { get ; }

		/// <summary>
		/// There are no comments for Zip in the schema.
		/// </summary>
		IObjectSet<nHydrate.LocationService.EFDAL.Interfaces.Entity.IZip> Zip { get ; }

		#region AddItem Method

		/// <summary>
		/// Adds an object to the object context.
		/// </summary>
		void AddItem(nHydrate.LocationService.EFDAL.Interfaces.Entity.IState entity);

		/// <summary>
		/// Adds an object to the object context.
		/// </summary>
		void AddItem(nHydrate.LocationService.EFDAL.Interfaces.Entity.IZip entity);

		#endregion

		#region DeleteItem Methods

		/// <summary>
		/// Adds an object to the object context.
		/// </summary>
		void DeleteItem(nHydrate.LocationService.EFDAL.Interfaces.Entity.IState entity);

		/// <summary>
		/// Adds an object to the object context.
		/// </summary>
		void DeleteItem(nHydrate.LocationService.EFDAL.Interfaces.Entity.IZip entity);

		#endregion

	}

	#endregion

	/// <summary />
	public partial interface IMetadata
	{
	}

	/// <summary />
	public partial interface IDTO
	{
	}

}

#pragma warning restore 0168
#pragma warning restore 0108
