delete from ZIP where City like '%Homeland %'
delete from ZIP where City like '% Public %'
delete from ZIP where City like '%Documents%'
delete from ZIP where City like '%Marketing%'
delete from ZIP where City like '%Of Indian%'
delete from ZIP where City like '% zip'
delete from ZIP where City like '% bank'
delete from ZIP where City like '% co'
delete from ZIP where City like '%corp of%'
delete from ZIP where City like '%Coast Guard%'
delete from ZIP where City like '%Computer%'
delete from ZIP where City like '%Prison%'
delete from ZIP where City like '%U S %'
delete from ZIP where City like '%Business%'
delete from ZIP where City like 'Naval%'
delete from ZIP where City like '%Commission%'
delete from ZIP where City like '% box %'
delete from ZIP where City like '% Assoc'
delete from ZIP where city like '%National%' and (LEN(city) - LEN(REPLACE(city,' ',''))) > 2
delete from ZIP where City like '%National Park%'
delete from ZIP where City like '% college'
delete from ZIP where City like '%Company%'
delete from ZIP where City like '%Facility%'
delete from ZIP where City like '%Correctional%'
delete from ZIP where City like '%The University%'
delete from ZIP where City like '%Postage%'
delete from ZIP where City like '%Univ Of%'
delete from ZIP where City like '%University Of%'
delete from ZIP where City like '%Natl%'
delete from ZIP where City like '%Med Center%'
delete from ZIP where City like '% School%'
delete from ZIP where City like '%Municipal%'
delete from ZIP where City like '%Utilities%'
delete from ZIP where City like '% Airport%'
delete from ZIP where City like '%zip code%'
delete from ZIP where City like '% inc'
delete from ZIP where City like '%hospital%'
delete from ZIP where City like '% corp'
delete from ZIP where City like '% comm'
delete from ZIP where City like '% elec%'
delete from ZIP where City like '% mem'
delete from ZIP where City like '%postal%'
delete from ZIP where City like '%office%'
delete from ZIP where City like '%of the%'
delete from ZIP where City like '%J C Penney%'
delete from ZIP where City like '%base %'
delete from ZIP where City like '%div of%'
delete from ZIP where City like '% gas'
delete from ZIP where City like '%on the%'
delete from ZIP where City like '%united%'
delete from ZIP where City like '%cancer%'
delete from ZIP where City like '%church of%'
delete from ZIP where City like '%govt%'
delete from ZIP where City like '%Naval Facility%'
delete from ZIP where City like '%life ins%'
delete from ZIP where City like '%regional%'
delete from ZIP where City like 'us %'
delete from ZIP where City like '% county%'
delete from ZIP where City like '%city of %'
delete from ZIP where City like '% & %'
delete from ZIP where City like '%Army%'
delete from ZIP where City like '%Ins Co%'
delete from ZIP where City like '%State Univ%'
delete from ZIP where City like '%Of Revenue%'
delete from ZIP where City like '%A F B%'
delete from ZIP where City like '%Bureau Of%'
delete from ZIP where City like '%Naval Air%'
delete from ZIP where City like '%Medical Ctr%'
delete from ZIP where City like '%Hsptl%'
delete from ZIP where City like '% dept%'
delete from ZIP where City like '% and %'
delete from ZIP where City like '%bank of%'
delete from ZIP where City like '%U S C C%'
delete from ZIP where City like '%G P O%'
delete from ZIP where City like '%Gas co%'
delete from ZIP where City like '%National Monu%'
delete from ZIP where City like '%airport%'
delete from ZIP where City like '%S U N Y%'
delete from ZIP where City like '%D O T N Y%'
delete from ZIP where City like '%State Campus%'
delete from ZIP where City like '%blue cross%'
delete from ZIP where City like '%air force%'
delete from ZIP where City like '%light co%'
delete from ZIP where City like '%Bank N A%'
delete from ZIP where city like '%University' and city <> 'University'
delete from ZIP where (LEN(city) - LEN(REPLACE(city,' ',''))) > 3

delete from zip where city = 'Atlanta Gas Light'
delete from zip where city = 'Goddard Flight Center'
delete from zip where city = 'La Power Light'
delete from zip where city = 'Texas Power Light'

delete from ZIP where City like '%Univ %'
delete from ZIP where City like '% Univ%'
delete from ZIP where City like '%gas of%'
delete from ZIP where City like '%Vehicle%'
delete from ZIP where City like '% power%'
delete from ZIP where City like '%bmc%'
delete from ZIP where City like '% ndc%'
delete from ZIP where City in ('3 M','88','A A R P','A M F Greensboro','Aaa','Aberdeen Proving Ground', 'Ameritech', 'I B M', 'B M G', 'E P A', 'N A S A', 'N B C')
delete from ZIP where City like '% tech%'
delete from ZIP where City like '%peniten%'
delete from ZIP where City like '% mail %'

delete from ZIP where City like '%Balance of%'
delete from city where name like '%Balance of%'
delete from city where name like '%(pt.)%'
delete from ZIP where City like '%Mortgage%'

delete from zip where city like '%Commercial%'
delete from zip where city like '%Dept Of%'
delete from zip where city like '%National Lab%'
delete from zip where city like '%State House%'
delete from zip where city like '%Indian Reservation%'
delete from zip where city like '%Shipyard%'
delete from zip where city like '%Finance%'
delete from zip where city like '% Seminary%'
delete from zip where city like '%Foundation%'
delete from zip where city like '%Fund Ins%'
delete from zip where city like '%afb%'
delete from zip where city like '%Insurance%'
delete from zip where city like '%Secretary Of%'
delete from zip where city like '%Motor%'
delete from zip where city like '%Assurance%'
delete from zip where city like '%Communications%'
delete from zip where city like '%Clearing House%'
delete from zip where city like '%Clear House%'
delete from zip where city like '%Lottery%'
delete from zip where city like '%Library%'
delete from zip where city like '% State %'
delete from zip where city like '%Court House%'
delete from zip where city like '%Courthouse%'
delete from zip where city like '%Licensing%'
delete from zip where city like '%Lic Div%'
delete from zip where city like '%Medical Center%'
delete from zip where city like '%U of %'
delete from zip where city like '%corpo%'
delete from zip where city like '%for christ%'
delete from zip where city like '%shops%'

--delete from city where Name like '%(balance)%'
--delete from city where Name like '%consolidated%'
--delete from city where Name like '%government%'
delete from city where Name like '%reservation'
delete from city where Name like '%county%'

GO
