delete from ZIP where City like '%Homeland %'
delete from ZIP where City like '% Public %'
delete from ZIP where City like '%Documents%'
delete from ZIP where City like '%Marketing%'
delete from ZIP where City like '%Of Indian%'
delete from ZIP where City like '% zip'
delete from ZIP where City like '% bank'
delete from ZIP where City like '% co'
delete from ZIP where City like '%corp of%'
delete from ZIP where City like '%Coast Guard%'
delete from ZIP where City like '%Computer%'
delete from ZIP where City like '%Prison%'
delete from ZIP where City like '%U S %'
delete from ZIP where City like '%Business%'
delete from ZIP where City like 'Naval%'
delete from ZIP where City like '%Commission%'
delete from ZIP where City like '% box %'
delete from ZIP where City like '% Assoc'
delete from ZIP where city like '%National%' and (LEN(city) - LEN(REPLACE(city,' ',''))) > 2
delete from ZIP where City like '%National Park%'
delete from ZIP where City like '% college'
delete from ZIP where City like '%Company%'
delete from ZIP where City like '%Facility%'
delete from ZIP where City like '%Correctional%'
delete from ZIP where City like '%The University%'
delete from ZIP where City like '%Postage%'
delete from ZIP where City like '%Univ Of%'
delete from ZIP where City like '%University Of%'
delete from ZIP where City like '%Natl%'
delete from ZIP where City like '%Med Center%'
delete from ZIP where City like '% School%'
delete from ZIP where City like '%Municipal%'
delete from ZIP where City like '%Utilities%'
delete from ZIP where City like '% Airport%'
delete from ZIP where City like '%zip code%'
delete from ZIP where City like '% inc'
delete from ZIP where City like '%hospital%'
delete from ZIP where City like '% corp'
delete from ZIP where City like '% comm'
delete from ZIP where City like '% elec%'
delete from ZIP where City like '% mem'
delete from ZIP where City like '%postal%'
delete from ZIP where City like '%office%'
delete from ZIP where City like '%of the%'
delete from ZIP where City like '%J C Penney%'
delete from ZIP where City like '%base %'
delete from ZIP where City like '%div of%'
delete from ZIP where City like '% gas'
delete from ZIP where City like '%on the%'
delete from ZIP where City like '%united%'
delete from ZIP where City like '%cancer%'
delete from ZIP where City like '%church of%'
delete from ZIP where City like '%govt%'
delete from ZIP where City like '%Naval Facility%'
delete from ZIP where City like '%life ins%'
delete from ZIP where City like '%regional%'
delete from ZIP where City like 'us %'
delete from ZIP where City like '% county%'
delete from ZIP where City like '%city of %'
delete from ZIP where City like '% & %'
delete from ZIP where City like '%Army%'
delete from ZIP where City like '%Ins Co%'
delete from ZIP where City like '%State Univ%'
delete from ZIP where City like '%Of Revenue%'
delete from ZIP where City like '%A F B%'
delete from ZIP where City like '%Bureau Of%'
delete from ZIP where City like '%Naval Air%'
delete from ZIP where City like '%Medical Ctr%'
delete from ZIP where City like '%Hsptl%'
delete from ZIP where City like '% dept%'
delete from ZIP where City like '% and %'
delete from ZIP where City like '%bank of%'
delete from ZIP where City like '%U S C C%'
delete from ZIP where City like '%G P O%'
delete from ZIP where City like '%Gas co%'
delete from ZIP where City like '%National Monu%'
delete from ZIP where City like '%airport%'
delete from ZIP where City like '%S U N Y%'
delete from ZIP where City like '%D O T N Y%'
delete from ZIP where City like '%State Campus%'
delete from ZIP where City like '%blue cross%'
delete from ZIP where City like '%air force%'
delete from ZIP where City like '%light co%'
delete from ZIP where City like '%Bank N A%'
delete from ZIP where city like '%University' and city <> 'University'
delete from ZIP where (LEN(city) - LEN(REPLACE(city,' ',''))) > 3

delete from zip where city = 'Atlanta Gas Light'
delete from zip where city = 'Goddard Flight Center'
delete from zip where city = 'La Power Light'
delete from zip where city = 'Texas Power Light'
GO